// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';

export const cssAnimationsTopics: Record<string, ContentTopic> = {
  'cssAnimations-configuring-an-animation': {
    id: 'cssAnimations-configuring-an-animation',
    heading: 'Configuring an animation',
    blocks: [
      {
        type: 'paragraph',
        text: 'To create a CSS animation sequence, you style the element you want to animate with the `animation` property or its sub-properties. This lets you configure the timing, duration, and other details of how the animation sequence should progress. This does not configure the actual appearance of the animation, which is done using the `@keyframes` at-rule as described in the Defining animation sequence using keyframes section below.',
      },
      {
        type: 'paragraph',
        text: 'The sub-properties of the `animation` property are:',
      },
      {
        type: 'definitions',
        items: [
          {
            term: '`animation-composition`',
            description:
              'Specifies the composite operation to use when multiple animations affect the same property simultaneously. This property is not part of the `animation` shorthand property.',
          },
          {
            term: '`animation-delay`',
            description:
              'Specifies the delay between an element loading and the start of an animation sequence and whether the animation should start immediately from its beginning or partway through the animation.',
          },
          {
            term: '`animation-direction`',
            description:
              "Specifies whether an animation's first iteration should be forward or backward and whether subsequent iterations should alternate direction on each run through the sequence or reset to the start point and repeat.",
          },
          {
            term: '`animation-duration`',
            description: 'Specifies the length of time in which an animation completes one cycle.',
          },
          {
            term: '`animation-fill-mode`',
            description:
              'Specifies how an animation applies styles to its target before and after it runs.',
          },
        ],
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'In the case of animation forwards fill mode, animated properties behave as if included in a set `will-change` property value. If a new stacking context was created during the animation, the target element retains the stacking context after the animation has finished.',
        },
      },
      {
        type: 'definitions',
        items: [
          {
            term: '`animation-iteration-count`',
            description: 'Specifies the number of times an animation should repeat.',
          },
          {
            term: '`animation-name`',
            description:
              "Specifies the name of the `@keyframes` at-rule describing an animation's keyframes.",
          },
          {
            term: '`animation-play-state`',
            description: 'Specifies whether to pause or play an animation sequence.',
          },
          {
            term: '`animation-timeline`',
            description:
              'Specifies the timeline that is used to control the progress of a CSS animation.',
          },
          {
            term: '`animation-timing-function`',
            description:
              'Specifies how an animation transitions through keyframes by establishing acceleration curves.',
          },
        ],
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Animations/Using',
  },
  'cssAnimations-defining-an-animation-sequence-using-keyframes': {
    id: 'cssAnimations-defining-an-animation-sequence-using-keyframes',
    heading: 'Defining an animation sequence using keyframes',
    blocks: [
      {
        type: 'paragraph',
        text: "After you've configured the animation's timing, you need to define the appearance of the animation. This is done by establishing one or more keyframes using the `@keyframes` at-rule. Each keyframe describes how the animated element should render at a given time during the animation sequence.",
      },
      {
        type: 'paragraph',
        text: 'Since the timing of the animation is defined in the CSS style that configures the animation, keyframes use a `percentage` to indicate the time during the animation sequence at which they take place. 0% indicates the first moment of the animation sequence, while 100% indicates the final state of the animation. Because these two times are so important, they have special aliases: `from` and `to`. Both are optional. If `from`/`0%` or `to`/`100%` is not specified, the browser starts or finishes the animation using the computed values of all attributes.',
      },
      {
        type: 'paragraph',
        text: 'You can optionally include additional keyframes that describe intermediate steps between the start and end of the animation.',
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Animations/Using',
  },
  'cssAnimations-using-the-animation-shorthand': {
    id: 'cssAnimations-using-the-animation-shorthand',
    heading: 'Using the animation shorthand',
    blocks: [
      {
        type: 'paragraph',
        text: "The `animation` shorthand is useful for saving space. As an example, some of the rules we've been using through this article:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'p {\n  animation-duration: 3s;\n  animation-name: slide-in;\n  animation-iteration-count: infinite;\n  animation-direction: alternate;\n}',
        },
      },
      {
        type: 'paragraph',
        text: '...could be replaced by using the `animation` shorthand.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'p {\n  animation: 3s infinite alternate slide-in;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'To learn more about the sequence in which different animation property values can be specified using the `animation` shorthand, see the `animation` reference page.',
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Animations/Using',
  },
  'cssAnimations-setting-multiple-animation-property-values': {
    id: 'cssAnimations-setting-multiple-animation-property-values',
    heading: 'Setting multiple animation property values',
    blocks: [
      {
        type: 'paragraph',
        text: "The CSS animation longhand properties can accept multiple values, separated by commas. This feature can be used when you want to apply multiple animations in a single rule and set different durations, iteration counts, etc., for each of the animations. Let's look at some quick examples to explain the different permutations.",
      },
      {
        type: 'paragraph',
        text: 'In this first example, there are three duration and three iteration count values. So each animation is assigned a value of duration and iteration count with the same position as the animation name. The `fadeInOut` animation is assigned a duration of `2.5s` and an iteration count of `2`, and the `bounce` animation is assigned a duration of `1s` and an iteration count of `5`.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'animation-name: fadeInOut, moveLeft300px, bounce;\nanimation-duration: 2.5s, 5s, 1s;\nanimation-iteration-count: 2, 1, 5;',
        },
      },
      {
        type: 'paragraph',
        text: "In this second example, three animation names are set, but there's only one duration and iteration count. In this case, all three animations are given the same duration and iteration count.",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'animation-name: fadeInOut, moveLeft300px, bounce;\nanimation-duration: 3s;\nanimation-iteration-count: 1;',
        },
      },
      {
        type: 'paragraph',
        text: 'In this third example, three animations are specified, but only two durations and iteration counts. In such cases where there are not enough values in the list to assign a separate one to each animation, the value assignment cycles from the first to the last item in the available list and then cycles back to the first item. So, `fadeInOut` gets a duration of `2.5s`, and `moveLeft300px` gets a duration of `5s`, which is the last value in the list of duration values. The duration value assignment now resets to the first value; `bounce`, therefore, gets a duration of `2.5s`. The iteration count values (and any other property values you specify) will be assigned in the same way.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'animation-name: fadeInOut, moveLeft300px, bounce;\nanimation-duration: 2.5s, 5s;\nanimation-iteration-count: 2, 1;',
        },
      },
      {
        type: 'paragraph',
        text: "If the mismatch in the number of animations and animation property values is inverted, say there are five `animation-duration` values for three `animation-name` values, then the extra or unused animation property values, in this case, two `animation-duration` values, don't apply to any animation and are ignored.",
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Animations/Using',
  },
  'cssAnimations-examples': {
    id: 'cssAnimations-examples',
    heading: 'Examples',
    blocks: [
      {
        type: 'subheading',
        level: 3,
        text: 'Making text slide across the browser window',
      },
      {
        type: 'paragraph',
        text: 'This basic example styles a `<p>` element using the `translate` and `scale` transition properties so that the text slides in from off the right edge of the browser window.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'p {\n  animation-duration: 3s;\n  animation-name: slide-in;\n}\n\n@keyframes slide-in {\n  from {\n    translate: 150vw 0;\n    scale: 200% 1;\n  }\n\n  to {\n    translate: 0 0;\n    scale: 100% 1;\n  }\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'In this example, the style for the `<p>` element specifies that the animation should take 3 seconds to execute from start to finish, using the `animation-duration` property and that the name of the `@keyframes` at-rule defining the keyframes for the animation sequence is `slide-in`.',
      },
      {
        type: 'paragraph',
        text: 'In this case, we have just two keyframes. The first occurs at `0%` (using the alias `from`). Here, we configure the `translate` property of the element to be at `150vw` (that is, beyond the far right edge of the containing element), and the `scale` of the element to be 200% (or two times its default inline size), causing the paragraph to be twice as wide as its `<body>` containing block. This causes the first frame of the animation to have the header drawn off the right edge of the browser window.',
      },
      {
        type: 'paragraph',
        text: 'The second keyframe occurs at `100%` (using the alias `to`). The `translate` property is set to `0%` and the `scale` of the element is set to `1`, which is `100%`. This causes the header to finish its animation in its default state, flush against the left edge of the content area.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p>\n  The Caterpillar and Alice looked at each other for some time in silence: at\n  last the Caterpillar took the hookah out of its mouth, and addressed her in a\n  languid, sleepy voice.\n</p>',
        },
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'Reload page to see the animation.',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Adding another keyframe animation',
      },
      {
        type: 'paragraph',
        text: "Let's add another keyframe to the previous example's animation. Let's say we want Alice's name to turn pink and grow and then shrink back to its original size and color as it moves from right to left. While we could change the `font-size`, changing any properties that impact the box model negatively impacts performance. Instead, we wrap her name in a `<span>` and then scale and assign a color to that separately. That requires adding a second animation impacting only the `<span>`:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '@keyframes grow-shrink {\n  25%,\n  75% {\n    scale: 100%;\n  }\n\n  50% {\n    scale: 200%;\n    color: magenta;\n  }\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'The full code now looks like this:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'p {\n  animation-duration: 3s;\n  animation-name: slide-in;\n}\np span {\n  display: inline-block;\n  animation-duration: 3s;\n  animation-name: grow-shrink;\n}\n\n@keyframes slide-in {\n  from {\n    translate: 150vw 0;\n    scale: 200% 1;\n  }\n\n  to {\n    translate: 0 0;\n    scale: 100% 1;\n  }\n}\n\n@keyframes grow-shrink {\n  25%,\n  75% {\n    scale: 100%;\n  }\n\n  50% {\n    scale: 200%;\n    color: magenta;\n  }\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'We\'ve added a `<span>` around "Alice":',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p>\n  The Caterpillar and <span>Alice</span> looked at each other for some time in\n  silence: at last the Caterpillar took the hookah out of its mouth, and\n  addressed her in a languid, sleepy voice.\n</p>',
        },
      },
      {
        type: 'paragraph',
        text: "This tells the browser the name should be normal for the first and last 25% of the animation, but turn pink while being scaled up and back again in the middle. We set the spans's `display` property to `inline-block` as the `transform` properties do not affect non-replaced inline-level content.",
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'Reload page to see the animation.',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Repeating the animation',
      },
      {
        type: 'paragraph',
        text: "To make the animation repeat itself, use the `animation-iteration-count` property to indicate how many times to repeat the animation. In this case, let's use `infinite` to have the animation repeat indefinitely:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'p {\n  animation-duration: 3s;\n  animation-name: slide-in;\n  animation-iteration-count: infinite;\n}',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '@keyframes slide-in {\n  from {\n    translate: 150vw 0;\n    scale: 200% 1;\n  }\n\n  to {\n    translate: 0 0;\n    scale: 100% 1;\n  }\n}',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p>\n  The Caterpillar and Alice looked at each other for some time in silence: at\n  last the Caterpillar took the hookah out of its mouth, and addressed her in a\n  languid, sleepy voice.\n</p>',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Making the animation move back and forth',
      },
      {
        type: 'paragraph',
        text: "That made it repeat, but it's very odd having it jump back to the start each time it begins animating. What we really want is for it to move back and forth across the screen. That's easily accomplished by setting `animation-direction` to `alternate`:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'p {\n  animation-duration: 3s;\n  animation-name: slide-in;\n  animation-iteration-count: infinite;\n  animation-direction: alternate;\n}',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '@keyframes slide-in {\n  from {\n    translate: 150vw 0;\n    scale: 200% 1;\n  }\n\n  to {\n    translate: 0 0;\n    scale: 100% 1;\n  }\n}',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p>\n  The Caterpillar and Alice looked at each other for some time in silence: at\n  last the Caterpillar took the hookah out of its mouth, and addressed her in a\n  languid, sleepy voice.\n</p>',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Using animation events',
      },
      {
        type: 'paragraph',
        text: 'You can get additional control over animations — as well as useful information about them — by making use of animation events. These events, represented by the `AnimationEvent` object, can be used to detect when animations start, finish, and begin a new iteration. Each event includes the time at which it occurred as well as the name of the animation that triggered the event.',
      },
      {
        type: 'paragraph',
        text: "We'll modify the sliding text example to output some information about each animation event when it occurs, so we can get a look at how they work.",
      },
      {
        type: 'paragraph',
        text: 'We\'ve included the same keyframe animation as the previous example. This animation will last 3 seconds, be called "slide-in", repeat 3 times, and travel in an alternate direction each time. In the `@keyframes`, the scale and translation are manipulated along the x-axis to make the element slide across the screen.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '.slide-in {\n  animation-duration: 3s;\n  animation-name: slide-in;\n  animation-iteration-count: 3;\n  animation-direction: alternate;\n}',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '@keyframes slide-in {\n  from {\n    translate: 150vw 0;\n    scale: 200% 1;\n  }\n\n  to {\n    translate: 0 0;\n    scale: 100% 1;\n  }\n}',
        },
      },
      {
        type: 'subheading',
        level: 4,
        text: 'Adding the animation event listeners',
      },
      {
        type: 'paragraph',
        text: "We'll use JavaScript code to listen for all three possible animation events. This code configures our event listeners; we call it when the document is first loaded in order to set things up.",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'js',
          code: 'const element = document.getElementById("watch-me");\nelement.addEventListener("animationstart", listener);\nelement.addEventListener("animationend", listener);\nelement.addEventListener("animationiteration", listener);\n\nelement.className = "slide-in";',
        },
      },
      {
        type: 'paragraph',
        text: 'This is pretty standard code; you can get details on how it works in the documentation for `eventTarget.addEventListener()`. The last thing this code does is set the `class` on the element we\'ll be animating to "slide-in"; we do this to start the animation.',
      },
      {
        type: 'paragraph',
        text: "Why? Because the `animationstart` event fires as soon as the animation starts, and in our case, that happens before our code runs. So we'll start the animation ourselves by setting the class of the element to the style that gets animated after the fact.",
      },
      {
        type: 'subheading',
        level: 4,
        text: 'Receiving the events',
      },
      {
        type: 'paragraph',
        text: 'The events get delivered to the `listener()` function, which is shown below.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'js',
          code: 'function listener(event) {\n  const l = document.createElement("li");\n  switch (event.type) {\n    case "animationstart":\n      l.textContent = `Started: elapsed time is ${event.elapsedTime}`;\n      break;\n    case "animationend":\n      l.textContent = `Ended: elapsed time is ${event.elapsedTime}`;\n      break;\n    case "animationiteration":\n      l.textContent = `New loop started at time ${event.elapsedTime}`;\n      break;\n  }\n  document.getElementById("output").appendChild(l);\n}',
        },
      },
      {
        type: 'paragraph',
        text: "This code, too, is very simple. It looks at the `event.type` to determine which kind of animation event occurred, then adds an appropriate note to the `<ul>` (unordered list) we're using to log these events.",
      },
      {
        type: 'paragraph',
        text: 'The output, when all is said and done, looks something like this:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'Started: elapsed time is 0',
          'New loop started at time 3.01200008392334',
          'New loop started at time 6.00600004196167',
          'Ended: elapsed time is 9.234000205993652',
        ],
      },
      {
        type: 'paragraph',
        text: "Note that the times are very close to, but not exactly, those expected given the timing established when the animation was configured. Note also that after the final iteration of the animation, the `animationiteration` event isn't sent; instead, the `animationend` event is sent.",
      },
      {
        type: 'paragraph',
        text: "Just for the sake of completeness, here's the HTML that displays the page content, including the list into which the script inserts information about the received events:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<h1 id="watch-me">Watch me move</h1>\n<p>\n  This example shows how to use CSS animations to make <code>H1</code>\n  elements move across the page.\n</p>\n<p>\n  In addition, we output some text each time an animation event fires, so you\n  can see them in action.\n</p>\n<ul id="output"></ul>',
        },
      },
      {
        type: 'paragraph',
        text: "And here's the live output.",
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'Reload page to see the animation.',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Animating display and content-visibility',
      },
      {
        type: 'paragraph',
        text: 'This example demonstrates how `display` and `content-visibility` can be animated. This behavior is useful for creating entry/exit animations where you want to for example remove a container from the DOM with `display: none`, but have it fade out smoothly with `opacity` rather than disappearing immediately.',
      },
      {
        type: 'paragraph',
        text: 'Supporting browsers animate `display` and `content-visibility` with a variation on the discrete animation type. This generally means that properties will flip between two values 50% of the way through animating between the two.',
      },
      {
        type: 'paragraph',
        text: 'There is an exception, however, which is when animating to/from `display: none` or `content-visibility: hidden` to a visible value. In this case, the browser will flip between the two values so that the animated content is shown for the entire animation duration.',
      },
      {
        type: 'paragraph',
        text: 'So for example:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'When animating `display` from `none` to `block` (or another visible `display` value), the value will flip to `block` at `0%` of the animation duration so it is visible throughout.',
          'When animating `display` from `block` (or another visible `display` value) to `none`, the value will flip to `none` at `100%` of the animation duration so it is visible throughout.',
        ],
      },
      {
        type: 'subheading',
        level: 4,
        text: 'HTML',
      },
      {
        type: 'paragraph',
        text: 'The HTML contains two `<p>` elements with a `<div>` in between that we will animate from `display` `none` to `block`.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p>\n  Click anywhere on the screen or press any key to toggle the\n  <code>&lt;div&gt;</code> between hidden and showing.\n</p>\n\n<div>\n  This is a <code>&lt;div&gt;</code> element that animates between\n  <code>display: none; opacity: 0</code> and\n  <code>display: block; opacity: 1</code>. Neat, huh?\n</div>\n\n<p>\n  This is another paragraph to show that <code>display: none;</code> is being\n  applied and removed on the above <code>&lt;div&gt; </code>. If only its\n  <code>opacity</code> was being changed, it would always take up the space in\n  the DOM.\n</p>',
        },
      },
      {
        type: 'subheading',
        level: 4,
        text: 'CSS',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'html {\n  height: 100vh;\n}\n\ndiv {\n  font-size: 1.6rem;\n  padding: 20px;\n  border: 3px solid red;\n  border-radius: 20px;\n  width: 480px;\n  opacity: 0;\n  display: none;\n}\n\n/* Animation classes */\n\ndiv.fade-in {\n  display: block;\n  animation: fade-in 0.7s ease-in forwards;\n}\n\ndiv.fade-out {\n  animation: fade-out 0.7s ease-out forwards;\n}\n\n/* Animation keyframes */\n\n@keyframes fade-in {\n  0% {\n    opacity: 0;\n    display: none;\n  }\n\n  100% {\n    opacity: 1;\n    display: block;\n  }\n}\n\n@keyframes fade-out {\n  0% {\n    opacity: 1;\n    display: block;\n  }\n\n  100% {\n    opacity: 0;\n    display: none;\n  }\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'Note the inclusion of the `display` property in the keyframe animations.',
      },
      {
        type: 'subheading',
        level: 4,
        text: 'JavaScript',
      },
      {
        type: 'paragraph',
        text: 'Finally, we include a bit of JavaScript to set up event listeners to trigger the animations. Specifically, we add the `fade-in` class to the `<div>` when we want it to appear, and `fade-out` when we want it to disappear.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'js',
          code: 'const divElem = document.querySelector("div");\nconst htmlElem = document.querySelector(":root");\n\nhtmlElem.addEventListener("click", showHide);\ndocument.addEventListener("keydown", showHide);\n\nfunction showHide() {\n  if (divElem.classList[0] === "fade-in") {\n    divElem.classList.remove("fade-in");\n    divElem.classList.add("fade-out");\n  } else {\n    divElem.classList.remove("fade-out");\n    divElem.classList.add("fade-in");\n  }\n}',
        },
      },
      {
        type: 'subheading',
        level: 4,
        text: 'Result',
      },
      {
        type: 'paragraph',
        text: 'The code renders as follows:',
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Animations/Using',
  },
};
