// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';
import selector from '../../assets/css/selector.png';

export const cssBasicSelectorsTopics: Record<string, ContentTopic> = {
  'cssBasicSelectors-what-is-a-selector': {
    id: 'cssBasicSelectors-what-is-a-selector',
    heading: 'What is a selector?',
    blocks: [
      {
        type: 'paragraph',
        text: 'A CSS selector is the first part of a CSS Rule. It is a pattern of elements and other terms that tell the browser which HTML elements should have the CSS property values inside the rule applied to them. The element or elements selected by the selector are referred to as the subject of the selector.',
      },
      {
        type: 'image',
        src: selector,
        alt: 'Some code with the h1 highlighted.',
      },
      {
        type: 'paragraph',
        text: "In earlier articles, you met various selectors and learned that there are selectors that target the document in different ways; for example, by selecting an element such as `h1`, or a class such as `.special`. Let's start by recapping the main ones you've already seen.",
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Basic_selectors',
  },
  'cssBasicSelectors-type-selectors': {
    id: 'cssBasicSelectors-type-selectors',
    heading: 'Type selectors',
    blocks: [
      {
        type: 'paragraph',
        text: 'A type selector is sometimes called a tag name selector or element selector because it selects an HTML tag/element in your document. In the example below, we have used the `span`, `em` and `strong` selectors.',
      },
      {
        type: 'htmlTable',
        html: '<h1>Type selectors</h1>\n<p>\n  Veggies es bonus vobis, proinde vos postulo essum magis\n  <span>kohlrabi welsh onion</span> daikon amaranth tatsoi tomatillo melon azuki\n  bean garlic.\n</p>\n\n<p>\n  Gumbo beet greens corn soko <strong>endive</strong> gumbo gourd. Parsley\n  shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra\n  wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.\n</p>\n\n<p>\n  Turnip greens yarrow ricebean rutabaga <em>endive cauliflower</em> sea lettuce\n  kohlrabi amaranth water spinach avocado daikon napa cabbage asparagus winter\n  purslane kale. Celery potato scallion desert raisin horseradish spinach\n</p>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'body {\n  font-family: sans-serif;\n}\n\nspan {\n  background-color: yellow;\n}\n\nstrong {\n  color: rebeccapurple;\n}\n\nem {\n  color: rebeccapurple;\n}',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Basic_selectors',
  },
  'cssBasicSelectors-class-selectors': {
    id: 'cssBasicSelectors-class-selectors',
    heading: 'Class selectors',
    blocks: [
      {
        type: 'paragraph',
        text: 'The case-sensitive class selector starts with a dot (`.`) character. It will select everything in the document with that class applied to it. In the live example below, we have created a class called `highlight` and applied it to several places in the document. All elements with that class are highlighted.',
      },
      {
        type: 'htmlTable',
        html: '<h1 class="highlight">Class selectors</h1>\n<p>\n  Veggies es bonus vobis, proinde vos postulo essum magis\n  <span class="highlight">kohlrabi welsh onion</span> daikon amaranth tatsoi\n  tomatillo melon azuki bean garlic.\n</p>\n\n<p class="highlight">\n  Gumbo beet greens corn soko <strong>endive</strong> gumbo gourd. Parsley\n  shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra\n  wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.\n</p>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'body {\n  font-family: sans-serif;\n}\n\n.highlight {\n  background-color: yellow;\n}',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Targeting classes on particular elements',
      },
      {
        type: 'paragraph',
        text: 'You can create a selector that will target specific elements with the class applied. In this next example, we will highlight a `<span>` with a class of `highlight` differently from an `<h1>` heading with a class of `highlight`. We do this by using the type selector for the element we want to target, with the class appended using a dot, with no white space in between.',
      },
      {
        type: 'htmlTable',
        html: '<h1 class="highlight">Class selectors</h1>\n<p>\n  Veggies es bonus vobis, proinde vos postulo essum magis\n  <span class="highlight">kohlrabi welsh onion</span> daikon amaranth tatsoi\n  tomatillo melon azuki bean garlic.\n</p>\n\n<p class="highlight">\n  Gumbo beet greens corn soko <strong>endive</strong> gumbo gourd. Parsley\n  shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra\n  wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.\n</p>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'body {\n  font-family: sans-serif;\n}\n\nspan.highlight {\n  background-color: yellow;\n}\n\nh1.highlight {\n  background-color: pink;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'This approach reduces the scope of a rule. The rule will only apply to that particular element and class combination. You would need to add another selector if you wanted the rule to apply to other elements.',
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Target an element if it has more than one class applied',
      },
      {
        type: 'paragraph',
        text: 'You can apply multiple classes to an element and target them individually, or only select the element when all of the classes in the selector are present. This can be helpful when building up components that can be combined in different ways on your site.',
      },
      {
        type: 'paragraph',
        text: 'In the example below, we have a `<div>` that contains a note. The gray border is applied when the box has a class of `notebox`. If it also has a class of `warning` or `danger`, we change the `border-color`.',
      },
      {
        type: 'paragraph',
        text: "We can tell the browser that we only want to match the element if it has two classes applied by chaining them together with no white space between them. You'll see that the last `<div>` doesn't get any styling applied, as it only has the `danger` class. To get any styles applied, it needs the `notebox` class as well.",
      },
      {
        type: 'htmlTable',
        html: '<div class="notebox">This is an informational note.</div>\n\n<div class="notebox warning">This note shows a warning.</div>\n\n<div class="notebox danger">This note shows danger!</div>\n\n<div class="danger">\n  This won\'t get styled — it also needs to have the notebox class\n</div>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'body {\n  font-family: sans-serif;\n}\n\n.notebox {\n  border: 4px solid #666666;\n  padding: 0.5em;\n  margin: 0.5em;\n}\n\n.notebox.warning {\n  border-color: orange;\n  font-weight: bold;\n}\n\n.notebox.danger {\n  border-color: red;\n  font-weight: bold;\n}',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Basic_selectors',
  },
  'cssBasicSelectors-id-selectors': {
    id: 'cssBasicSelectors-id-selectors',
    heading: 'ID selectors',
    blocks: [
      {
        type: 'paragraph',
        text: 'The case-sensitive ID selector begins with a `#` rather than a dot character, but is used in the same way as a class selector. The difference is that an ID can be used only once per page, and elements can only have a single `id` value. An ID selector selects an element with a specific `id`, and you can precede the ID with a type selector to only target the element if both the element and ID match. You can see both of these uses in the following example:',
      },
      {
        type: 'htmlTable',
        html: '<h1 id="heading">ID selector</h1>\n<p>\n  Veggies es bonus vobis, proinde vos postulo essum magis kohlrabi welsh onion\n  daikon amaranth tatsoi tomatillo melon azuki bean garlic.\n</p>\n\n<p id="one">\n  Gumbo beet greens corn soko <strong>endive</strong> gumbo gourd. Parsley\n  shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra\n  wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.\n</p>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'body {\n  font-family: sans-serif;\n}\n\n#one {\n  background-color: yellow;\n}\n\nh1#heading {\n  color: rebeccapurple;\n}',
        },
      },
      {
        type: 'paragraph',
        text: "> [!WARNING] > Using the same ID multiple times in a document may appear to work for styling purposes, but don't do this. It results in invalid code and will cause strange behavior in many places.",
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Playing with ID selectors',
      },
      {
        type: 'paragraph',
        text: 'Try editing the above example to make the following changes:',
      },
      {
        type: 'list',
        ordered: true,
        items: [
          'Edit the HTML to apply the `#one` styles to the first paragraph rather than the second.',
          'Edit the CSS to modify the declarations inside the ID selectors, and note how this changes the look of the HTML.',
        ],
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Basic_selectors',
  },
  'cssBasicSelectors-selector-lists': {
    id: 'cssBasicSelectors-selector-lists',
    heading: 'Selector lists',
    blocks: [
      {
        type: 'paragraph',
        text: 'If you want to apply the same CSS to multiple items, you can combine individual selectors into a selector list. The rule is then applied to all the individual selectors. For example, if I have the same CSS for an `h1` and a `.special` selector, I could write this as two separate rules.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'h1 {\n  color: blue;\n}\n\n.special {\n  color: blue;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'I could also combine these into a selector list by adding a comma between them.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'h1, .special {\n  color: blue;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'White space is valid before or after the comma. You may also find the selectors more readable if each is on a new line.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'h1,\n.special {\n  color: blue;\n}',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Playing with selector lists',
      },
      {
        type: 'paragraph',
        text: 'In the example below, try combining the two selectors that have identical declarations. The visual display should be the same afterwards.',
      },
      {
        type: 'htmlTable',
        html: '<h1>Type selectors</h1>\n<p>\n  Veggies es bonus vobis, proinde vos postulo essum magis\n  <span>kohlrabi welsh onion</span> daikon amaranth tatsoi tomatillo melon azuki\n  bean garlic.\n</p>\n\n<p>\n  Gumbo beet greens corn soko <strong>endive</strong> gumbo gourd. Parsley\n  shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra\n  wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.\n</p>\n\n<p>\n  Turnip greens yarrow ricebean rutabaga <em>endive cauliflower</em> sea lettuce\n  kohlrabi amaranth water spinach avocado daikon napa cabbage asparagus winter\n  purslane kale. Celery potato scallion desert raisin horseradish spinach\n</p>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'body {\n  font-family: sans-serif;\n}\nspan {\n  background-color: yellow;\n}\n\nstrong {\n  color: rebeccapurple;\n}\n\nem {\n  color: rebeccapurple;\n}',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Invalid selectors in selector lists',
      },
      {
        type: 'paragraph',
        text: 'When you group selectors in this way, if any selector is syntactically invalid, the whole rule will be ignored.',
      },
      {
        type: 'paragraph',
        text: 'In the following example, the invalid class selector rule will be ignored, whereas the `h1` would still be styled.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'h1 {\n  color: blue;\n}\n\n..special {\n  color: blue;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'When combined, however, neither the `h1` nor the class will be styled as the entire rule is deemed invalid.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'h1, ..special {\n  color: blue;\n}',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Basic_selectors',
  },
  'cssBasicSelectors-the-universal-selector': {
    id: 'cssBasicSelectors-the-universal-selector',
    heading: 'The universal selector',
    blocks: [
      {
        type: 'paragraph',
        text: 'The universal selector is indicated by an asterisk (`*`). It selects everything in the document. If `*` is chained using a descendant combinator, it selects everything inside that ancestor element. For example, `p *` selects all the nested elements inside the `<p>` element.',
      },
      {
        type: 'paragraph',
        text: "In the following example, we use the universal selector to remove the margins on all elements. Instead of the browser's default styling, which spaces out headings and paragraphs with margins, everything is close together.",
      },
      {
        type: 'htmlTable',
        html: '<h1>Universal selector</h1>\n<p>\n  Veggies es bonus vobis, proinde vos postulo essum magis\n  <span>kohlrabi welsh onion</span> daikon amaranth tatsoi tomatillo melon azuki\n  bean garlic.\n</p>\n\n<p>\n  Gumbo beet greens corn soko <strong>endive</strong> gumbo gourd. Parsley\n  shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra\n  wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.\n</p>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'body {\n  font-family: sans-serif;\n}\n\n* {\n  margin: 0;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'This kind of behavior can sometimes be seen in "reset stylesheets", which strip out all of the browser styling. Since the universal selector makes global changes, we use it for very specific situations, such as the one described below.',
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Using the universal selector to make your selectors easier to read',
      },
      {
        type: 'paragraph',
        text: 'One use of the universal selector is to make selectors easier to read and more intuitive. For example, if we wanted to select all descendant elements of an `<article>` element that are the first child of their parent, including direct children, we could use the `:first-child` pseudo-class. We will learn more about this in pseudo-classes and pseudo-elements:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'article :first-child {\n  font-weight: bold;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'However, this selector could be confused with `article:first-child`, which will select any `<article>` element that is the first child of another element.',
      },
      {
        type: 'paragraph',
        text: 'To avoid this confusion, we could add the universal selector to the `:first-child` pseudo-class, so it is more obvious what the selector is doing. It is selecting any element that is the first-child of an `<article>` element, or the first-child of any descendant element of `<article>`:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'article *:first-child {\n  font-weight: bold;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'Both are equivalent, but some people find the second option easier to read.',
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: "You are unlikely to see this technique used much in published websites. We don't use it much on MDN, for example. However, you should still consider using it in your code if you find it easier to understand.",
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Basic_selectors',
  },
  'cssBasicSelectors-summary': {
    id: 'cssBasicSelectors-summary',
    heading: 'Summary',
    blocks: [
      {
        type: 'paragraph',
        text: "In this article, we've recapped CSS selectors, which enable you to target particular HTML elements, looking at type, class, and ID selectors in a bit more depth than we did previously. In the next article, we will dive into attribute selectors.",
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'For a complete list of selectors, see our CSS selectors reference.',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Basic_selectors',
  },
};
