// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';

export const cssClampTopics: Record<string, ContentTopic> = {
  'cssClamp-syntax': {
    id: 'cssClamp-syntax',
    heading: 'Syntax',
    blocks: [
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '/* Static values */\nwidth: clamp(200px, 40%, 400px);\nwidth: clamp(20rem, 30vw, 70rem);\nwidth: clamp(10vw, 20em, 100vw);\n\n/* Calculated values */\nwidth: clamp(min(10vw, 20rem), 300px, max(90vw, 55rem));\nwidth: clamp(100px, calc(30% / 2rem + 10px), 900px);',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Parameters',
      },
      {
        type: 'paragraph',
        text: 'The `clamp(min, val, max)` function accepts three comma-separated expressions as its parameters.',
      },
      {
        type: 'definitions',
        items: [
          {
            term: '`min`',
            description:
              'The minimum value is the smallest (most negative) value. This is the lower bound in the range of allowed values. If the preferred value is less than this value, the minimum value will be used.',
          },
          {
            term: '`val`',
            description:
              'The preferred value is the expression whose value will be used as long as the result is between the minimum and maximum values.',
          },
          {
            term: '`max`',
            description:
              'The maximum value is the largest (most positive) expression value to which the value of the property will be assigned if the preferred value is greater than this upper bound.',
          },
        ],
      },
      {
        type: 'paragraph',
        text: 'The expressions can be math functions (see `calc()` for more information), literal values, other expressions that evaluate to a valid argument type (like `&lt;length&gt;`), or nested `min()` and `max()` functions. For math expressions, you can use addition, subtraction, multiplication, and division without using the `calc()` function itself. You may also use parentheses to establish computation order when needed.',
      },
      {
        type: 'paragraph',
        text: 'You can use different units for each value in your expressions and different units in any math function making up any of the arguments.',
      },
      {
        type: 'paragraph',
        text: 'Keep the following aspects in mind while working with the function:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'Math expressions involving percentages for widths and heights on table columns, table column groups, table rows, table row groups, and table cells in both auto and fixed layout tables may be treated as if `auto` had been specified.',
          'It is permitted to nest `max()` and `min()` functions as expression values, in which case the inner ones are treated as basic parentheses. The expressions are full math expressions, so you can use direct addition, subtraction, multiplication and division without using the `calc()` function itself.',
          'The expression can be values combining the addition (`+`), subtraction (`-`), multiplication (`*`), and division (`/`) operators, using standard operator precedence rules. Make sure to put a space on each side of the `+` and `-` operands. You can use different units for each value in your expression. You may also use parentheses to establish computation order when needed.',
          'Oftentimes you will want to use `min()` and `max()` within a `clamp()` function.',
        ],
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Return value',
      },
      {
        type: 'paragraph',
        text: '`clamp(MIN, VAL, MAX)` is resolved as `max(MIN, min(VAL, MAX))`.',
      },
      {
        type: 'paragraph',
        text: 'Based on the provided parameters, the function returns `&lt;length&gt;`, `&lt;frequency&gt;`, `angle`, `&lt;time&gt;`, `&lt;percentage&gt;`, `&lt;number&gt;`, or `&lt;integer&gt;`.',
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/clamp',
  },
  'cssClamp-formal-syntax': {
    id: 'cssClamp-formal-syntax',
    heading: 'Formal syntax',
    blocks: [
      {
        type: 'paragraph',
        text: '{{CSSSyntax}}',
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/clamp',
  },
  'cssClamp-examples': {
    id: 'cssClamp-examples',
    heading: 'Examples',
    blocks: [
      {
        type: 'subheading',
        level: 3,
        text: 'min(), max(), and clamp() comparison',
      },
      {
        type: 'paragraph',
        text: 'In this example we have a web page that uses `min()`, `max()`, and `clamp()` to set sizes responsively.',
      },
      {
        type: 'paragraph',
        text: 'The example adjusts the sizes of page elements in three ways:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'the lengths of the lines of text',
          'the font size of paragraph text',
          'the font size of heading text',
        ],
      },
      {
        type: 'paragraph',
        text: 'In all three cases, the page uses a combination of a viewport-relative units (`vw` and `percentage`), to set a size that varies with the viewport width, and a value that is not viewport relative (`rem` and `px`) to implement minimum and/or maximum sizes.',
      },
      {
        type: 'paragraph',
        text: 'The example is at . Open it in a new window and try adjusting the window width.',
      },
      {
        type: 'paragraph',
        text: "The line length (controlled by the `width` of the `<body>` element) will increase as the window width increases, but only up to a certain point (`1000px`), and beyond that point, it won't increase anymore. We're using `min()` to set a maximum line length: it can go under `1000px`, but won't go over. This is helpful because long lines are harder to read, so we often want to limit how long a line can be. To achieve this we use `min(1000px, calc(70% + 100px))`: when the result of the percentage-based calculation goes above `1000px`, we switch to the fixed `1000px` value.",
      },
      {
        type: 'paragraph',
        text: "The size of the paragraph text, controlled by the `font-size` of the `<p>` element, decreases as the window gets narrower, but only up to a certain point, and beyond that point (the point where `1.2vw` is less than `1.2rem`) it doesn't get any smaller: it stays at `1.2rem`. We're using `max()` to set a minimum font size: the font can grow above `1.2rem` but will never go below it. This is helpful because really small text is hard to read. To achieve this we use `max(1.2rem, 1.2vw)`. This means that the `font-size` will be set at `1.2rem`, unless the computed value of `1.2vw` is greater than that of `1.2rem`, in which case it will be set to `1.2vw` instead.",
      },
      {
        type: 'paragraph',
        text: 'The size of the heading text, controlled by the `font-size` of the `<h1>` element, has a viewport-relative value with both a maximum and a minimum threshold. To achieve this we use `clamp(1.8rem, 2.5vw, 2.8rem)`. The viewport-relative value is `2.5vw` but it is clamped between `1.8rem` and `2.8rem`, so:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'if the calculated value of `2.5vw` is less than `1.8rem`, then `1.8rem` will be used',
          'if the calculated value of `2.5vw` is greater than `2.8rem`, then `2.8rem` will be used.',
        ],
      },
      {
        type: 'paragraph',
        text: 'This prevents the heading text from getting too small in a very narrow window, or too big in a very wide window.',
      },
      {
        type: 'subheading',
        level: 4,
        text: 'HTML',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<h1>Basic responsive test</h1>\n<p>\n  Lorem ipsum dolor sit amet, consectetur adipiscing elit. In orci orci,\n  eleifend id risus nec, mattis rutrum velit. Suspendisse fringilla egestas erat\n  eu convallis. Phasellus eu velit ut magna dapibus elementum cursus at ligula.\n  Ut tempus varius nibh, nec auctor sapien iaculis sit amet. Fusce iaculis,\n  libero quis elementum viverra, nulla ante accumsan lectus, sit amet convallis\n  lacus ipsum vel est. Curabitur et urna non est consectetur pulvinar vel id\n  risus. Ut vestibulum, sem in semper aliquet, felis arcu euismod sapien, ac\n  imperdiet massa nisl quis sem. Vestibulum ac elementum felis, in tempor velit.\n  Pellentesque purus ex, mattis at ornare quis, porta condimentum mi. Donec\n  vestibulum ligula vel nulla blandit, quis euismod nulla vestibulum.\n  Suspendisse potenti. Nunc neque mauris, tempor sed facilisis at, ultrices eget\n  nulla. Pellentesque convallis ante nec augue porttitor, id tempus ante luctus.\n</p>\n\n<p>\n  Integer rutrum sollicitudin tellus, quis cursus nulla scelerisque nec. Nunc eu\n  facilisis lorem. Maecenas faucibus sapien eleifend, semper tellus at, pharetra\n  quam. Cras feugiat vulputate tortor at rhoncus. Class aptent taciti sociosqu\n  ad litora torquent per conubia nostra, per inceptos himenaeos. Nam non felis\n  quis sem lobortis sodales vel id libero. Phasellus sit amet placerat lorem.\n</p>',
        },
      },
      {
        type: 'subheading',
        level: 4,
        text: 'CSS',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'html {\n  font-family: sans-serif;\n}\n\nbody {\n  margin: 0 auto;\n  width: min(1000px, calc(70% + 100px));\n}\n\nh1 {\n  letter-spacing: 2px;\n  font-size: clamp(1.8rem, 2.5vw, 2.8rem);\n}\n\np {\n  line-height: 1.5;\n  font-size: max(1.2rem, 1.2vw);\n}',
        },
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/clamp',
  },
  'cssClamp-accessibility': {
    id: 'cssClamp-accessibility',
    heading: 'Accessibility',
    blocks: [
      {
        type: 'paragraph',
        text: 'When `clamp()` is used for controlling text size, make sure that the maximum allowed value is a relative length unit that is no less than twice the minimum allowed value, for example:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'font-size: clamp(1rem, 2.5vw, 2rem);',
        },
      },
      {
        type: 'paragraph',
        text: 'This helps to ensure that text size can scale to at least 200% if the page is zoomed.',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'MDN Understanding WCAG, Guideline 1.4 explanations',
          'Understanding Success Criterion 1.4.4: Resize Text | WAI | W3C',
        ],
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/clamp',
  },
};
