// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';

export const cssCustomPropertiesTopics: Record<string, ContentTopic> = {
  'cssCustomProperties-declaring-custom-properties': {
    id: 'cssCustomProperties-declaring-custom-properties',
    heading: 'Declaring custom properties',
    blocks: [
      {
        type: 'paragraph',
        text: 'In CSS, you can declare a custom property using two dashes as a prefix for the property name, or by using the `@property` at-rule. The following sections describe how to use these two methods.',
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Using a prefix of two dashes (`--`)',
      },
      {
        type: 'paragraph',
        text: 'A custom property prefixed with two dashes begins with `--`, followed by the property name (e.g., `--my-property`), and a property value that can be any valid CSS value. Like any other property, this is written inside a ruleset. The following example shows how to create a custom property `--main-bg-color` and uses a `named-color` value of `brown`:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'section {\n  --main-bg-color: brown;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'The selector given to the ruleset (`<section>` elements in the example above) defines the scope in which the custom property can be used. For this reason, a common practice is to define custom properties on the `:root` pseudo-class, so that it can be referenced globally:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: ':root {\n  --main-bg-color: brown;\n}',
        },
      },
      {
        type: 'paragraph',
        text: "This doesn't always have to be the case: you maybe have a good reason for limiting the scope of your custom properties.",
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'Custom property names are case sensitive — `--my-color` will be treated as a separate custom property to `--My-color`.',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Using the `@property` at-rule',
      },
      {
        type: 'paragraph',
        text: 'The `@property` at-rule allows you to be more expressive with the definition of a custom property with the ability to associate a type with the property, set default values, and control inheritance. The following example creates a custom property called `--logo-color` which expects a `&lt;color&gt;`:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '@property --logo-color {\n  syntax: "<color>";\n  inherits: false;\n  initial-value: #c0ffee;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'If you want to define or work with custom properties in JavaScript instead of directly in CSS, there is a corresponding API for this purpose. You can read about how this works in the CSS Properties and Values API page.',
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Referencing custom properties with `var()`',
      },
      {
        type: 'paragraph',
        text: 'Regardless of which method you choose to define a custom property, you use them by referencing the property in a `var()` function in place of a standard property value:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'details {\n  background-color: var(--main-bg-color);\n}',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascading_variables/Using_custom_properties',
  },
  'cssCustomProperties-first-steps-with-custom-properties': {
    id: 'cssCustomProperties-first-steps-with-custom-properties',
    heading: 'First steps with custom properties',
    blocks: [
      {
        type: 'paragraph',
        text: "Let's start with some HTML that we would like to apply some styles to. There is a `<div>` that acts as a container that includes some child elements, some with nested elements:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<div class="container">\n  <div class="one">\n    <p>One</p>\n  </div>\n  <div class="two">\n    <p>Two</p>\n    <div class="three">\n      <p>Three</p>\n    </div>\n  </div>\n  <input class="four" placeholder="Four" />\n  <textarea class="five">Five</textarea>\n</div>',
        },
      },
      {
        type: 'paragraph',
        text: "We will use the following CSS to style a few different elements based on their classes (some layout rules are not shown below so we can focus on colors). Depending on their classes, we're giving elements `teal` or `pink` background colors:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '/* Set fonts, borders and padding */\nbody,\ntextarea,\n::placeholder {\n  font-family: sans-serif;\n  color: white;\n}\n\ndiv,\ninput,\ntextarea {\n  border: 2px black solid;\n  padding: 4px;\n  margin: 4px;\n}\n\n.container {\n  display: grid;\n  gap: 10px;\n}',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '/* For each class, set some colors */\n.one {\n  background-color: teal;\n}\n\n.two {\n  color: black;\n  background-color: pink;\n}\n\n.three {\n  color: white;\n  background-color: teal;\n}\n\n.four {\n  background-color: teal;\n}\n\n.five {\n  background-color: teal;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'This produces the following result:',
      },
      {
        type: 'paragraph',
        text: "There's an opportunity to use custom properties to replace repetitive values across these rules. After defining `--main-bg-color` in the `.container` scope and referencing its value in multiple places, the updated styles look like this:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '/* Define --main-bg-color here */\n.container {\n  --main-bg-color: teal;\n}\n\n/* For each class, set some colors */\n.one {\n  background-color: var(--main-bg-color);\n}\n\n.two {\n  color: black;\n  background-color: pink;\n}\n\n.three {\n  color: white;\n  background-color: var(--main-bg-color);\n}\n\n.four {\n  background-color: var(--main-bg-color);\n}\n\n.five {\n  background-color: var(--main-bg-color);\n}',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascading_variables/Using_custom_properties',
  },
  'cssCustomProperties-using-the-root-pseudo-class': {
    id: 'cssCustomProperties-using-the-root-pseudo-class',
    heading: 'Using the :root pseudo-class',
    blocks: [
      {
        type: 'paragraph',
        text: 'For some CSS declarations, it is possible to declare this higher in the cascade and let CSS inheritance solve this problem. For non-trivial projects, this is not always possible. By declaring a custom property on the `:root` pseudo-class and using it where needed throughout the document, a CSS author can reduce the need for repetition:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '/* Define --main-bg-color here */\n:root {\n  --main-bg-color: teal;\n}\n\n/* For each class, set some colors */\n.one,\n.three,\n.four,\n.five {\n  background-color: var(--main-bg-color);\n}\n\n.two {\n  color: black;\n  background-color: pink;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'This leads to the same result as the previous example, yet allows for one canonical declaration of the desired property value (`--main-bg-color: teal;`), which is very useful if you want to change the value across the entire project later.',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascading_variables/Using_custom_properties',
  },
  'cssCustomProperties-inheritance-of-custom-properties': {
    id: 'cssCustomProperties-inheritance-of-custom-properties',
    heading: 'Inheritance of custom properties',
    blocks: [
      {
        type: 'paragraph',
        text: 'A custom property defined using two dashes `--` instead of `@property` always inherits the value of its parent. This is demonstrated in the following example:',
      },
      {
        type: 'htmlTable',
        html: '<div class="one">\n  <p>One</p>\n  <div class="two">\n    <p>Two</p>\n    <div class="three"><p>Three</p></div>\n    <div class="four"><p>Four</p></div>\n  </div>\n</div>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'div {\n  background-color: var(--box-color);\n}\n\n.two {\n  --box-color: teal;\n}\n\n.three {\n  --box-color: pink;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'The results of `var(--box-color)` depending on inheritance are as follows:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          '`class="one"`: invalid value, which is the default value of a custom property defined in this way',
          '`class="two"`: `teal`',
          '`class="three"`: `pink`',
          '`class="four"`: `teal` (inherited from its parent)',
        ],
      },
      {
        type: 'paragraph',
        text: "One aspect of custom properties that the examples above demonstrate is that they don't behave exactly like variables in other programming languages. The value is computed where it is needed, not stored and reused in other places of a stylesheet. For instance, you cannot set a property's value and expect to retrieve the value in a sibling's descendant's rule. The property is only set for the matching selector and its descendants.",
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Using `@property` to control inheritance',
      },
      {
        type: 'paragraph',
        text: "The `@property` at-rule lets you explicitly state whether the property inherits or not. The following example creates a custom property using the `@property` at-rule. Inheritance is disabled, there's a `&lt;color&gt;` data type defined, and an initial value of `teal`.",
      },
      {
        type: 'paragraph',
        text: 'The parent element sets `--box-color` to a value of `green` and uses `--box-color` as a value for its background color. The child element also uses `background-color: var(--box-color)`, and we would expect it to have the color `green` if inheritance was enabled (or if it was defined using the double dash syntax).',
      },
      {
        type: 'htmlTable',
        html: '<div class="parent">\n  <p>Parent element</p>\n  <div class="child">\n    <p>Child element with inheritance disabled for --box-color.</p>\n  </div>\n</div>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: '@property --box-color {\n  syntax: "<color>";\n  inherits: false;\n  initial-value: teal;\n}\n\n.parent {\n  --box-color: green;\n  background-color: var(--box-color);\n}\n\n.child {\n  width: 80%;\n  height: 40%;\n  background-color: var(--box-color);\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'Because `inherits: false;` is set in the at-rule, and a value for the `--box-color` property is not declared within the `.child` scope, the initial value of `teal` is used instead of `green` that would have been inherited from the parent:',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascading_variables/Using_custom_properties',
  },
  'cssCustomProperties-custom-property-fallback-values': {
    id: 'cssCustomProperties-custom-property-fallback-values',
    heading: 'Custom property fallback values',
    blocks: [
      {
        type: 'paragraph',
        text: 'You can define fallback values for custom properties using the `var()` function, and the `initial-value` of the `@property` at-rule.',
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: "Fallback values aren't used to fix compatibility issues for when CSS custom properties are not supported, as the fallback value won't help in this case. Fallbacks cover the case where the browser supports CSS custom properties and is able to use a different value if the desired variable isn't defined yet or has an invalid value.",
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Defining fallbacks in the `var()` function',
      },
      {
        type: 'paragraph',
        text: 'Using the `var()` function, you can define multiple fallback values when the given variable is not yet defined; this can be useful when working with Custom Elements and Shadow DOM.',
      },
      {
        type: 'paragraph',
        text: 'The first argument to the function is the name of the custom property. The second argument to the function is an optional fallback value, which is used as the substitution value when the referenced custom property is invalid. The function accepts two parameters, assigning everything following the first comma as the second parameter. If the second parameter is invalid, the fallback will fail. For example:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '.one {\n  /* Red if --my-var is not defined */\n  color: var(--my-var, red);\n}\n\n.two {\n  /* pink if --my-var and --my-background are not defined */\n  color: var(--my-var, var(--my-background, pink));\n}\n\n.three {\n  /* Invalid: "--my-background, pink" */\n  color: var(--my-var, --my-background, pink);\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'Including a custom property as a fallback, as seen in the second example above (`var(--my-var, var(--my-background, pink))`), is the correct way to provide more than one fallback with `var()`. You should be aware of the performance impact of this method, however, as it takes more time to parse through the nested variables.',
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'The syntax of the fallback, like that of custom properties, allows commas. For example, `var(--foo, red, blue)` defines a fallback of `red, blue` — anything between the first comma and the end of the function is considered a fallback value.',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Fallbacks using the `@property` initial value',
      },
      {
        type: 'paragraph',
        text: "Aside from using `var()`, the `initial-value` defined in the `@property` at-rule can be used as a fallback mechanism. In fact, we've already seen this in the `@property` inheritance section.",
      },
      {
        type: 'paragraph',
        text: '<!-- cSpell:ignore peenk -->',
      },
      {
        type: 'paragraph',
        text: "The following example sets an initial value of `--box-color` to `teal` using the `@property` at-rule. In the ruleset following the at-rule, we want to set `--box-color` to `pink`, but there's a typo in the value name. The same is true for the third `<div>` where we've used `2rem` for the custom property that's expecting a valid `<color>` value. Both `2rem` and `peenk` are invalid color values, so the initial value of `teal` is applied:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: '@property --box-color {\n  syntax: "<color>";\n  initial-value: teal;\n  inherits: false;\n}\n\n.one {\n  --box-color: pink;\n  background-color: var(--box-color);\n}\n\n.two {\n  --box-color: peenk;\n  background-color: var(--box-color);\n}\n\n.three {\n  --box-color: 2rem;\n  background-color: var(--box-color);\n}',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascading_variables/Using_custom_properties',
  },
  'cssCustomProperties-invalid-custom-properties': {
    id: 'cssCustomProperties-invalid-custom-properties',
    heading: 'Invalid custom properties',
    blocks: [
      {
        type: 'paragraph',
        text: "Each CSS property can be assigned a defined set of values. If you try to assign a value to a property that is outside its set of valid values, it's considered invalid.",
      },
      {
        type: 'paragraph',
        text: 'When the browser encounters an invalid value for a regular CSS property (for example, a value of `16px` for the `color` property), it discards the declaration, and elements are assigned the values that they would have had if the declaration did not exist. In the following example, we see what happens when a regular CSS declaration is invalid; `color: 16px;` is discarded and the previous `color: blue` rule is applied instead:',
      },
      {
        type: 'htmlTable',
        html: '<p>This paragraph is initially black.</p>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'p {\n  font-weight: bold;\n  color: blue;\n}\n\np {\n  /* oops, not a valid color */\n  color: 16px;\n}',
        },
      },
      {
        type: 'paragraph',
        text: "However, when the values of custom properties are parsed, the browser doesn't yet know where they will be used, so it must consider nearly all values as valid. Unfortunately, these valid values can be used, via the `var()` functional notation, in a context where they might not make sense. Properties and custom variables can lead to invalid CSS statements, leading to the concept of valid at computed time.",
      },
      {
        type: 'paragraph',
        text: 'When the browser encounters an invalid `var()` substitution, then the initial or inherited value of the property is used. This example is just like the last one, except we use a custom property.',
      },
      {
        type: 'paragraph',
        text: "The browser substitutes the value of `--text-color` in place of `var(--text-color)`, but `16px` is not a valid property value for `color`. After substitution, the property doesn't make sense, so the browser handles this situation in two steps:",
      },
      {
        type: 'list',
        ordered: true,
        items: [
          "Check if the property `color` is inheritable. It is, but this `<p>` doesn't have any parent with the `color` property set. So we move on to the next step.",
          'Set the value to its default initial value, which is black.',
        ],
      },
      {
        type: 'htmlTable',
        html: '<p>This paragraph is initially black.</p>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: ':root {\n  --text-color: 16px;\n}\n\np {\n  font-weight: bold;\n  color: blue;\n}\n\np {\n  color: var(--text-color);\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'For such cases, the `@property` at-rule can prevent unexpected results by allowing you to define the initial value of the property:',
      },
      {
        type: 'htmlTable',
        html: '<p>This paragraph is initially black.</p>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: '@property --text-color {\n  syntax: "<color>";\n  inherits: false;\n  initial-value: teal;\n}\n\n:root {\n  --text-color: 16px;\n}\n\np {\n  font-weight: bold;\n  color: blue;\n}\n\np {\n  color: var(--text-color);\n}',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascading_variables/Using_custom_properties',
  },
  'cssCustomProperties-values-in-javascript': {
    id: 'cssCustomProperties-values-in-javascript',
    heading: 'Values in JavaScript',
    blocks: [
      {
        type: 'paragraph',
        text: 'To use the values of custom properties in JavaScript, it is just like standard properties.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'js',
          code: '// get variable from inline style\nelement.style.getPropertyValue("--my-var");\n\n// get variable from wherever\ngetComputedStyle(element).getPropertyValue("--my-var");\n\n// set variable on inline style\nelement.style.setProperty("--my-var", jsVar + 4);',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascading_variables/Using_custom_properties',
  },
};
