// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';
import flexTerms from '../../assets/css/flex_terms.png';

export const cssFlexboxTopics: Record<string, ContentTopic> = {
  'cssFlexbox-why-flexbox': {
    id: 'cssFlexbox-why-flexbox',
    heading: 'Why flexbox?',
    blocks: [
      {
        type: 'paragraph',
        text: 'CSS flexible box layout enables you to:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'Vertically center a block of content inside its parent.',
          'Make all the children of a container take up an equal amount of the available width/height, regardless of how much width/height is available.',
          'Make all columns in a multiple-column layout adopt the same height even if they contain a different amount of content.',
        ],
      },
      {
        type: 'paragraph',
        text: "Flexbox features may be the perfect solution for your one dimensional layout needs. Let's dig in and find out!",
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-introducing-a-simple-example': {
    id: 'cssFlexbox-introducing-a-simple-example',
    heading: 'Introducing a simple example',
    blocks: [
      {
        type: 'htmlTable',
        html: '<header>\n  <h1>Sample flexbox example</h1>\n</header>\n<section>\n  <article>\n    <h2>First article</h2>\n    <p>Content…</p>\n  </article>\n  <article>\n    <h2>Second article</h2>\n    <p>Content…</p>\n  </article>\n  <article>\n    <h2>Third article</h2>\n    <p>Content…</p>\n  </article>\n</section>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'body {\n  font-family: sans-serif;\n  margin: 0;\n}\nheader {\n  background: purple;\n  height: 100px;\n}\nh1 {\n  text-align: center;\n  color: white;\n  line-height: 100px;\n  margin: 0;\n}\nsection {\n  zoom: 0.8;\n}\narticle {\n  padding: 10px;\n  margin: 10px;\n  background: aqua;\n}\n/* Add your flexbox CSS below here */',
        },
      },
      {
        type: 'paragraph',
        text: "You'll see that we have a `<header>` element with a top level heading inside it and a `<section>` element containing three `<article>`s. We're going to use these to create a fairly standard three column layout.",
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-specifying-what-elements-to-lay-out-as-flexible-boxes': {
    id: 'cssFlexbox-specifying-what-elements-to-lay-out-as-flexible-boxes',
    heading: 'Specifying what elements to lay out as flexible boxes',
    blocks: [
      {
        type: 'paragraph',
        text: 'To start with, we need to select which elements are to be laid out as flexible boxes. To do this, we set a special value of `display` on the parent element of the elements you want to affect. In this case we want to lay out the `<article>` elements, so we set this on the `<section>`:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'section {\n  display: flex;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'This causes the `<section>` element to become a flex container and its children become flex items. This is what it looks like:',
      },
      {
        type: 'paragraph',
        text: 'This single declaration gives us everything we need. Incredible, right? We have a multiple column layout with equal-sized columns, and the columns are all the same height. This is because the default values given to flex items (the children of the flex container) are set up to solve common problems such as this.',
      },
      {
        type: 'paragraph',
        text: "Let's recap what's happening here. Adding a `display` value of `flex` to an element makes it a flex container. The container is displayed as Block-level content in terms of how it interacts with the rest of the page. When the element is converted to a flex container, its children are converted to (and laid out as) flex items.",
      },
      {
        type: 'paragraph',
        text: "You can make the container inline using an outside `display` value (e.g., `display: inline flex`), which affects how the container itself is laid out in the page. The legacy `inline-flex` display value displays the container as inline as well. We'll focus on how the contents of the container behave in this tutorial, but if you want to see the effect of inline versus block layout, you can have a look at the value comparison on the `display` property page.",
      },
      {
        type: 'paragraph',
        text: 'The next sections explain in more detail what flex items are and what happens inside an element when you make it a flex container.',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-the-flex-model': {
    id: 'cssFlexbox-the-flex-model',
    heading: 'The flex model',
    blocks: [
      {
        type: 'paragraph',
        text: 'When elements are laid out as flex items, they are laid out along two axes:',
      },
      {
        type: 'image',
        src: flexTerms,
        alt: 'Three flex items in a left-to-right language are laid out side-by-side in a flex container. The main axis — the axis of the flex container in the direction in which the flex items are laid out — is horizontal. The ends of the axis are main-start and main-end and are on the left and right respectively. The cross axis is vertical; perpendicular to the main axis. The cross-start and cross-end are at the top and bottom respectively. The length of the flex item along the main axis, in this case, the width, is called the main size, and the length of the flex item along the cross axis, in this case, the height, is called the cross size.',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'The main axis is the axis running in the direction the flex items are laid out in (for example, as a row across the page, or a column down the page.) The start and end points of this axis are called the main start and main end. The length of a flex item along the main axis is the main size.',
          'The cross axis is the axis running perpendicular to the direction the flex items are laid out in. The start and end points of this axis are called the cross start and cross end. The length of a flex item along the cross axis is the cross size.',
          'The parent element that has `display: flex` set on it (the `<section>` in our example) is called the flex container.',
          'The items laid out as flexible boxes inside the flex container are called flex items (the `<article>` elements in our example).',
        ],
      },
      {
        type: 'paragraph',
        text: 'Bear this terminology in mind as you go through subsequent sections. You can always refer back to it if you get confused about any of the terms being used.',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-columns-or-rows': {
    id: 'cssFlexbox-columns-or-rows',
    heading: 'Columns or rows?',
    blocks: [
      {
        type: 'paragraph',
        text: "Flexbox provides a property called `flex-direction` that specifies which direction the main axis runs (which direction the flexbox children are laid out in). By default this is set to `row`, which causes them to be laid out in a row in the direction your browser's default language works in (left to right, in the case of an English browser).",
      },
      {
        type: 'paragraph',
        text: 'Try adding the following declaration to your `<section>` rule:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'flex-direction: column;',
        },
      },
      {
        type: 'paragraph',
        text: "You'll see that this puts the items back in a column layout, much like they were before we added any CSS. Before you move on, delete this declaration from your example.",
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'You can also lay out flex items in a reverse direction using the `row-reverse` and `column-reverse` values. Experiment with these values too!',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-wrapping': {
    id: 'cssFlexbox-wrapping',
    heading: 'Wrapping',
    blocks: [
      {
        type: 'paragraph',
        text: "One issue that arises when you have a fixed width or height in your layout is that eventually your flexbox children will overflow their container, breaking the layout. In the following example we have 5 `<article>`s, which don't fit, because they have a `min-width` of `400px`, so there is a horizontal scroll.",
      },
      {
        type: 'paragraph',
        text: 'Here we see that the children are indeed breaking out of their container. By default, the browser tries to place all the flex items in a single row if the `flex-direction` is set to `row` or a single column if the `flex-direction` is set to `column`.',
      },
      {
        type: 'paragraph',
        text: 'One way in which you can fix this is to add the following declaration to your `<section>` rule:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'section {\n  flex-wrap: wrap;\n}',
        },
      },
      {
        type: 'paragraph',
        text: "You'll see that the layout looks much better with this included:",
      },
      {
        type: 'paragraph',
        text: 'We now have multiple rows. Each row has as many flexbox children fitted into it as is sensible. Any overflow is moved down to the next line.',
      },
      {
        type: 'paragraph',
        text: "But there's more we can do here. First of all, try changing your `flex-direction` property value to `row-reverse`. Now you'll see that you still have your multiple row layout, but it starts from the opposite corner of the browser window and flows in reverse.",
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-flex-flow-shorthand': {
    id: 'cssFlexbox-flex-flow-shorthand',
    heading: 'flex-flow shorthand',
    blocks: [
      {
        type: 'paragraph',
        text: "At this point it's worth noting that a shorthand exists for `flex-direction` and `flex-wrap`: `flex-flow`. So, for example, you can replace",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'flex-direction: row;\nflex-wrap: wrap;',
        },
      },
      {
        type: 'paragraph',
        text: 'with',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'flex-flow: row wrap;',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-flexible-sizing-of-flex-items': {
    id: 'cssFlexbox-flexible-sizing-of-flex-items',
    heading: 'Flexible sizing of flex items',
    blocks: [
      {
        type: 'paragraph',
        text: "Let's now return to our first example and look at how we can control what proportion of space flex items take up compared to the other flex items.",
      },
      {
        type: 'paragraph',
        text: 'In your local copy, add the following rule to the bottom of your CSS:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'article {\n  flex: 1;\n}',
        },
      },
      {
        type: 'paragraph',
        text: "This is a unitless proportion value that dictates how much available space along the main axis each flex item will take up compared to other flex items. In this case, we're giving each `<article>` element the same value (a value of `1`), which means they'll all take up an equal amount of the spare space left after properties like padding and margin have been set. This value is proportionally shared among the flex items: giving each flex item a value of `400000` would have exactly the same effect.",
      },
      {
        type: 'paragraph',
        text: 'Now add the following rule below the previous one:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'article:nth-of-type(3) {\n  flex: 2;\n}',
        },
      },
      {
        type: 'paragraph',
        text: "Now when you refresh, you'll see that the third `<article>` takes up twice as much of the available width as the other two. There are now four proportion units available in total (since 1 + 1 + 2 = 4). The first two flex items have one unit each, so they each take 1/4 of the available space. The third one has two units, so it takes up 2/4 of the available space (or one-half).",
      },
      {
        type: 'paragraph',
        text: 'You can also specify a minimum size value within the flex value. Try updating your existing article rules like so:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'article {\n  flex: 1 100px;\n}\n\narticle:nth-of-type(3) {\n  flex: 2 100px;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'This basically states, "Each flex item will first be given `100px` of the available space. After that, the rest of the available space will be shared according to the proportion units." You\'ll see a difference in how the space is shared.',
      },
      {
        type: 'paragraph',
        text: "All the flex items have a minimum width of 100 pixels—set using 'flex'. The value of flex for first two flex items is 1 and for the third item is 2. This splits the remaining space in the flex container into 4 proportion units. One unit is assigned to each of the first two flex items and 2 units are assigned to the third flex item, making the third flex item wider than the other two, which are of the same width.",
      },
      {
        type: 'paragraph',
        text: 'The real value of flexbox can be seen in its flexibility/responsiveness. If you resize the browser window or add another `<article>` element, the layout continues to work just fine.',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-flex-shorthand-versus-longhand': {
    id: 'cssFlexbox-flex-shorthand-versus-longhand',
    heading: 'flex: shorthand versus longhand',
    blocks: [
      {
        type: 'paragraph',
        text: '`flex` is a shorthand property that can specify up to three different values:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'The unitless proportion value we discussed above. This can be specified separately using the `flex-grow` longhand property.',
          "A second unitless proportion value, `flex-shrink`, which comes into play when the flex items are overflowing their container. This value specifies how much an item will shrink in order to prevent overflow. This is quite an advanced flexbox feature and we won't be covering it any further in this article.",
          'The minimum size value we discussed above. This can be specified separately using the `flex-basis` longhand value.',
        ],
      },
      {
        type: 'paragraph',
        text: "We'd advise against using the longhand flex properties unless you really have to (for example, to override something previously set). They lead to a lot of extra code being written and can be somewhat confusing.",
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-horizontal-and-vertical-alignment': {
    id: 'cssFlexbox-horizontal-and-vertical-alignment',
    heading: 'Horizontal and vertical alignment',
    blocks: [
      {
        type: 'paragraph',
        text: "You can also use flexbox features to align flex items along the main or cross axis. Let's explore this by looking at a new example:",
      },
      {
        type: 'htmlTable',
        html: '<div>\n  <button>Smile</button>\n  <button>Laugh</button>\n  <button>Wink</button>\n  <button>Shrug</button>\n  <button>Blush</button>\n</div>',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'body {\n  font-family: sans-serif;\n  width: 90%;\n  max-width: 960px;\n  margin: 10px auto;\n}\ndiv {\n  height: 100px;\n  border: 1px solid black;\n}\nbutton {\n  font-size: 18px;\n  line-height: 1.5;\n  width: 15%;\n}\n/* Add your flexbox CSS below here */',
        },
      },
      {
        type: 'paragraph',
        text: "We're going to turn this into a neat, flexible button/toolbar. At the moment you'll see a horizontal menu bar with some buttons jammed into the top left-hand corner.",
      },
      {
        type: 'paragraph',
        text: 'First, take a local copy of this example.',
      },
      {
        type: 'paragraph',
        text: "Now, add the following to the bottom of the example's CSS:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'div {\n  display: flex;\n  align-items: center;\n  justify-content: space-around;\n}',
        },
      },
      {
        type: 'paragraph',
        text: "Refresh the page and you'll see that the buttons are now nicely centered horizontally and vertically. We've done this via two new properties. The flex items are positioned at the center of the cross-axis by setting the `align-items` property to `center`. The flex items are spaced evenly along the main-axis by setting the `justify-content` property to `space-around`.",
      },
      {
        type: 'paragraph',
        text: 'The `align-items` property controls where the flex items sit on the cross axis.',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          "By default, the value `normal` which behaves as `stretch` in flexbox. This stretches all flex items to fill the parent in the direction of the cross axis. If the parent doesn't have a fixed size in the cross axis direction, then all flex items will become as tall (or wide) as the tallest (or widest) flex item. This is how our first example had columns of equal height by default.",
          "The `center` value that we used in our above code causes the items to maintain their intrinsic dimensions, but be centered along the cross axis. This is why our current example's buttons are centered vertically.",
          'You can also have values like `flex-start`, `self-start` or `start` and `flex-end`, `self-end` or `end`, which will align all items at the start and end of the cross axis respectively. The `baseline` values will line up the flex items by their baseline; basically the bottom of each flex items first line of text will be lined up with the bottom of the first line of the element with the greatest distance between the cross start and that baseline. See `align-items` for the full details.',
        ],
      },
      {
        type: 'paragraph',
        text: 'You can override the `align-items` behavior for individual flex items by applying the `align-self` property to them. For example, try adding the following to your CSS:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css-live-sample',
          code: 'button:first-child {\n  align-self: flex-end;\n}',
        },
      },
      {
        type: 'paragraph',
        text: "Have a look at what effect this has and remove it again when you've finished.",
      },
      {
        type: 'paragraph',
        text: '`justify-content` controls where the flex items sit on the main axis.',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'The default value is `normal`, which behaves as `start`, which makes all the items sit at the start of the main axis.',
          'You can use `end` or `flex-end` to make them sit at the end.',
          'The `left` and `right` values behave as `start` or `end` depending on the writing mode direction.',
          "`center` is also a value for `justify-content`. It'll make the flex items sit in the center of the main axis.",
          "The value we've used above, `space-around`, is useful — it distributes all the items evenly along the main axis with a bit of space left at either end.",
          "There is another value, `space-between`, which is very similar to `space-around` except that it doesn't leave any space at either end.",
        ],
      },
      {
        type: 'paragraph',
        text: 'The `justify-items` property is ignored in flexbox layouts.',
      },
      {
        type: 'paragraph',
        text: "We'd like to encourage you to play with these values to see how they work before you continue.",
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-ordering-flex-items': {
    id: 'cssFlexbox-ordering-flex-items',
    heading: 'Ordering flex items',
    blocks: [
      {
        type: 'paragraph',
        text: 'Flexbox also has a feature for changing the layout order of flex items without affecting the source order. This is another thing that is impossible to do with traditional layout methods.',
      },
      {
        type: 'paragraph',
        text: 'Try adding the following CSS to your button bar example code:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'button:first-child {\n  order: 1;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'Refresh and you\'ll see that the "Smile" button has moved to the end of the main axis. Let\'s talk about how this works in a bit more detail:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'By default, all flex items have an `order` value of `0`.',
          'Flex items with higher specified order values will appear later in the display order than items with lower order values.',
          'Flex items with the same order value will appear in their source order. So if you have four items whose order values have been set as `2`, `1`, `1`, and `0` respectively, their display order would be 4th, 2nd, 3rd, then 1st.',
          'The 3rd item appears after the 2nd because it has the same order value and is after it in the source order.',
        ],
      },
      {
        type: 'paragraph',
        text: 'You can set negative order values to make items appear earlier than items whose value is `0`. For example, you could make the "Blush" button appear at the start of the main axis using the following rule:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'button:last-child {\n  order: -1;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'While you can change the order using `order`, the tabbing order remains the same as the code order. Changing the order of focusable elements can negatively impact usability for your keyboard users!',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-nested-flex-boxes': {
    id: 'cssFlexbox-nested-flex-boxes',
    heading: 'Nested flex boxes',
    blocks: [
      {
        type: 'paragraph',
        text: "It's possible to create some pretty complex layouts with flexbox. It's perfectly OK to set a flex item to also be a flex container, so that its children are also laid out like flexible boxes.",
      },
      {
        type: 'paragraph',
        text: "This complex layout has a few flex items that are also flex containers. The HTML for this is fairly straightforward. We've got a `<section>` element containing three `<article>`s. The third `<article>` contains three `<div>`s, and the first `<div>` contains five `<button>`s:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'plain',
          code: 'section - article\n          article\n          article - div - button\n                    div   button\n                    div   button\n                          button\n                          button',
        },
      },
      {
        type: 'paragraph',
        text: "Let's look at the code we've used for the layout.",
      },
      {
        type: 'paragraph',
        text: 'First of all, we set the children of the `<section>` to be laid out as flexible boxes.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'section {\n  display: flex;\n}',
        },
      },
      {
        type: 'paragraph',
        text: "Next, we set some flex values on the `<article>`s themselves. Take special note of the second rule here: we're setting the third `<article>` to have its children laid out like flex items too, but this time we're laying them out like a column.",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'article {\n  flex: 1 100px;\n}\n\narticle:nth-of-type(3) {\n  flex: 3 100px;\n  display: flex;\n  flex-flow: column;\n}',
        },
      },
      {
        type: 'paragraph',
        text: 'Next, we select the first `<div>`. We first use `flex: 1 100px;` to effectively give it a minimum height of `100px`, then we set its children (the `<button>` elements) to also be laid out like flex items. Here we lay them out in a wrapping row and align them in the center of the available space as we did with the individual button example we saw earlier.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'article:nth-of-type(3) div:first-child {\n  flex: 1 100px;\n  display: flex;\n  flex-flow: row wrap;\n  align-items: center;\n  justify-content: space-around;\n}',
        },
      },
      {
        type: 'paragraph',
        text: "Finally, we set some sizing on the button. This time by giving it a flex value of `1 auto`. This has a very interesting effect, which you'll see if you try resizing your browser window width. The buttons will take up as much space as they can. As many will fit on a line as is comfortable; beyond that, they'll drop to a new line.",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: 'button {\n  flex: 1 auto;\n  margin: 5px;\n  font-size: 18px;\n  line-height: 1.5;\n}',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
  'cssFlexbox-summary': {
    id: 'cssFlexbox-summary',
    heading: 'Summary',
    blocks: [
      {
        type: 'paragraph',
        text: "That concludes our tour of the basics of flexbox. We hope you had fun and will have a good play around with it as you proceed further with your learning. In the next article, we'll give you some tests that you can use to check how well you've understood and retained all this information.",
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox',
  },
};
