// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';

export const cssPrefersReducedMotionTopics: Record<string, ContentTopic> = {
  'cssPrefersReducedMotion-syntax': {
    id: 'cssPrefersReducedMotion-syntax',
    heading: 'Syntax',
    blocks: [
      {
        type: 'definitions',
        items: [
          {
            term: '`no-preference`',
            description:
              'Indicates that a user has made no preference known on the device. This keyword value evaluates as false.',
          },
          {
            term: '`reduce`',
            description:
              'Indicates that a user has enabled the setting on their device for reduced motion. The `reduce` keyword value evaluates as true; therefore, `@media (prefers-reduced-motion)` is equivalent to `@media (prefers-reduced-motion: reduce)`.',
          },
        ],
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/At-rules/@media/prefers-reduced-motion',
  },
  'cssPrefersReducedMotion-user-preferences': {
    id: 'cssPrefersReducedMotion-user-preferences',
    heading: 'User preferences',
    blocks: [
      {
        type: 'paragraph',
        text: 'Use the following settings to honor the `reduce` request:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'In GTK/GNOME: Settings > Accessibility > Seeing > turn on "Reduced animation".',
          'In older versions of GNOME, GNOME Tweaks > General tab (or Appearance, depending on version) > Animations is turned off.',
          'Alternatively, add `gtk-enable-animations = false` to the `[Settings]` block of the GTK 3 configuration file.',
          'Additionally, try running `gsettings set org.gnome.desktop.interface enable-animations false` to make Firefox (and other programs relying on GTK version 4) respect the `reduce` setting.',
          'In Plasma/KDE: System Settings > Workspace Behavior > General Behavior > set "Animation speed" to "Instant".',
          'Alternatively, add `AnimationDurationFactor=0` to the `[KDE]` block of `~/.config/kdeglobals`.',
          'Or just run `kwriteconfig6 --key AnimationDurationFactor 0` in your terminal.',
          'In Windows 10: Settings > Ease of Access > Display > Show animations in Windows.',
          'In Windows 11: Settings > Accessibility > Visual Effects > Animation Effects.',
          'In macOS up to 15 (Sequoia): System Settings > Accessibility > Display > Reduce motion.',
          'In macOS 25 (Tahoe) onwards: System Settings > Accessibility > Motion > Reduce motion.',
          'In iOS: Settings > Accessibility > Motion.',
          'In Android 9+: Settings > Accessibility > Remove animations.',
          'In Firefox `about:config`: Add a number preference called `ui.prefersReducedMotion` and set its value to either `0` for full animation or to `1` to indicate a preference for reduced motion. Changes to this preference take effect immediately.',
        ],
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/At-rules/@media/prefers-reduced-motion',
  },
  'cssPrefersReducedMotion-examples': {
    id: 'cssPrefersReducedMotion-examples',
    heading: 'Examples',
    blocks: [
      {
        type: 'paragraph',
        text: 'This example uses a scaling animation to demonstrate `prefers-reduced-motion`. If you enable the setting for reducing motion in the accessibility preferences on your device, the `prefers-reduced-motion` media query will detect your preference and the CSS within the reduced motion rules, with the same specificity but coming later in the CSS source order, will take precedence. As a result, the animation on the box will tone down to the `dissolve` animation, which is a more muted animation that is not a vestibular motion trigger.',
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Toning down the animation scaling',
      },
      {
        type: 'subheading',
        level: 4,
        text: 'HTML',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<div class="animation">animated box</div>',
        },
      },
      {
        type: 'subheading',
        level: 4,
        text: 'CSS',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '.animation {\n  animation: pulse 1s linear infinite both;\n  background-color: purple;\n}\n\n/* Tone down the animation to avoid vestibular motion triggers. */\n@media (prefers-reduced-motion: reduce) {\n  .animation {\n    animation: dissolve 4s linear infinite both;\n    background-color: green;\n    text-decoration: overline;\n  }\n}',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'css',
          code: '.animation {\n  color: white;\n  font: 1.2em sans-serif;\n  width: 10em;\n  padding: 1em;\n  border-radius: 1em;\n  text-align: center;\n}\n\n@keyframes pulse {\n  0% {\n    transform: scale(1);\n  }\n  25% {\n    transform: scale(0.9);\n  }\n  50% {\n    transform: scale(1);\n  }\n  75% {\n    transform: scale(1.1);\n  }\n  100% {\n    transform: scale(1);\n  }\n}\n\n@keyframes dissolve {\n  0% {\n    opacity: 1;\n  }\n  50% {\n    opacity: 0.3;\n  }\n  100% {\n    opacity: 1;\n  }\n}',
        },
      },
      {
        type: 'subheading',
        level: 4,
        text: 'Result',
      },
      {
        type: 'paragraph',
        text: 'You can enable the setting for reducing motion on your device to view the change in animation scaling. This example uses the background color and the line over the text to visually highlight when the keyframe animation switches in response to the setting being enabled or disabled.',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/At-rules/@media/prefers-reduced-motion',
  },
};
