// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';

export const stylelintGettingStartedTopics: Record<string, ContentTopic> = {
  'stylelintGettingStarted-linting-css': {
    id: 'stylelintGettingStarted-linting-css',
    heading: 'Linting CSS',
    blocks: [
      {
        type: 'paragraph',
        text: 'Use npm and our create tool to automatically setup Stylelint and extend our standard config:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'shell',
          code: 'npm create stylelint@latest',
        },
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'note',
          body: 'Stylelint is also compatible with the Bun, pnpm, and Yarn package managers. You can use your preferred one to set up Stylelint, e.g. bun create stylelint or pnpm create stylelint.',
        },
      },
    ],
  },
  'stylelintGettingStarted-manual-setup': {
    id: 'stylelintGettingStarted-manual-setup',
    heading: 'Manual setup',
    blocks: [
      {
        type: 'paragraph',
        text: 'Alternatively, you can manually setup Stylelint to lint CSS.',
      },
      {
        type: 'list',
        ordered: true,
        items: [
          'Create a stylelint.config.mjs configuration file in the root of your project with the following content:',
          'Use npm (or your preferred package manager) to add the related dependencies:',
          'Run Stylelint on all the CSS files in your project:',
        ],
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'js',
          code: '/** @type {import(\'stylelint\').Config} */export default {  extends: ["stylelint-config-standard"]};',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'shell',
          code: 'npm add -D stylelint stylelint-config-standard',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'shell',
          code: 'npx stylelint "**/*.css"',
        },
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'note',
          body: 'The npx command allows you to run locally installed tools.\nYou can also use your preferred package manager\'s equivalent, e.g. bunx stylelint "**/*.css" or pnpm dlx stylelint "**/*.css".\nWe\'ll omit npx in the rest of this guide.',
        },
      },
      {
        type: 'paragraph',
        text: "Once you're up and running, you can customize Stylelint.",
      },
    ],
  },
  'stylelintGettingStarted-linting-css-like-languages-and-css-within-containers': {
    id: 'stylelintGettingStarted-linting-css-like-languages-and-css-within-containers',
    heading: 'Linting CSS-like languages and CSS within containers',
    blocks: [
      {
        type: 'paragraph',
        text: 'You can extend a community config to lint:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'CSS-like languages, e.g. SCSS, Sass and Less',
          'CSS within containers, e.g. in HTML, CSS-in-JS and Vue SFCs',
        ],
      },
      {
        type: 'paragraph',
        text: 'For example, to lint SCSS you can extend the SCSS community config:',
      },
      {
        type: 'list',
        ordered: true,
        items: [
          'Create a stylelint.config.mjs configuration file in the root of your project with the following content:',
          'Use npm (or your preferred package manager) to add the related dependencies:',
          'Run Stylelint on all the SCSS files in your project:',
        ],
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'js',
          code: '/** @type {import(\'stylelint\').Config} */export default {  extends: ["stylelint-config-standard-scss"]};',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'shell',
          code: 'npm add -D stylelint stylelint-config-standard-scss',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'shell',
          code: 'stylelint "**/*.scss"',
        },
      },
      {
        type: 'paragraph',
        text: 'The config includes the:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'SCSS syntax - a custom syntax to parse SCSS',
          'SCSS plugin - a set of custom rules for SCSS',
        ],
      },
      {
        type: 'paragraph',
        text: "You'll find more community configs in Awesome Stylelint.",
      },
    ],
  },
  'stylelintGettingStarted-using-a-custom-syntax-directly': {
    id: 'stylelintGettingStarted-using-a-custom-syntax-directly',
    heading: 'Using a custom syntax directly',
    blocks: [
      {
        type: 'paragraph',
        text: "If a shared config isn't available for your preferred language or container, you can install the appropriate custom syntax and use the customSyntax option yourself.",
      },
      {
        type: 'paragraph',
        text: 'For example, to lint CSS inside of Lit elements using the Lit custom syntax:',
      },
      {
        type: 'list',
        ordered: true,
        items: [
          'Create a stylelint.config.mjs configuration file in the root of your project with the following content:',
          'Use npm (or your preferred package manager) to add the related dependencies:',
          'Run Stylelint on all the JavaScript files in your project:',
        ],
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'js',
          code: '/** @type {import(\'stylelint\').Config} */export default {  extends: "stylelint-config-standard",  customSyntax: "postcss-lit"};',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'shell',
          code: 'npm add -D stylelint stylelint-config-standard postcss-lit',
        },
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'shell',
          code: 'stylelint "**/*.js"',
        },
      },
      {
        type: 'paragraph',
        text: "You'll find more custom syntaxes in Awesome Stylelint.",
      },
    ],
  },
  'stylelintGettingStarted-using-more-than-one-custom-syntax': {
    id: 'stylelintGettingStarted-using-more-than-one-custom-syntax',
    heading: 'Using more than one custom syntax',
    blocks: [
      {
        type: 'paragraph',
        text: 'If you want to lint more than one language or container, you can use the overrides property.',
      },
      {
        type: 'paragraph',
        text: 'For example, to lint CSS files and the CSS within Lit Elements you can update your configuration to:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'js',
          code: '/** @type {import(\'stylelint\').Config} */export default {  extends: ["stylelint-config-standard"],  overrides: [    {      files: ["*.js"],      customSyntax: "postcss-lit"    }  ]};',
        },
      },
      {
        type: 'paragraph',
        text: 'And then run Stylelint on both your CSS and JavaScript files:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'shell',
          code: 'stylelint "**/*.{css,js}"',
        },
      },
    ],
  },
};
