// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';

export const stylelintTopics: Record<string, ContentTopic> = {
  'stylelint-overview': {
    id: 'stylelint-overview',
    heading: 'Stylelint',
    blocks: [
      {
        type: 'paragraph',
        text: 'Stylelint is a CSS linter that helps you avoid errors and enforce conventions.',
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Features',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'Over 100 built-in rules for modern CSS syntax and features.',
          'Supports plugins for creating custom rules.',
          'Automatically fixes problems where possible.',
          'Supports shareable configurations that you can create or extend.',
          'Can be customized to your exact needs.',
          'Supports embedded styles from HTML, Markdown, and CSS-in-JS template literals.',
          'Supports CSS-like languages such as SCSS, Sass, Less, and SugarSS.',
        ],
      },
      {
        type: 'subheading',
        level: 3,
        text: 'How Stylelint helps',
      },
      {
        type: 'paragraph',
        text: 'Stylelint helps avoid errors such as malformed grid areas, problematic duplicate selectors, and misspelled property names.',
      },
      {
        type: 'paragraph',
        text: 'It can also enforce conventions such as naming patterns for custom properties, limits on the number of ID selectors, allowed units, and notation for modern color functions.',
      },
      {
        type: 'paragraph',
        text: 'Stylelint recommends using a pretty printer such as Prettier alongside it. Linters and pretty printers are complementary tools that help produce consistent and error-free code.',
      },
    ],
    sourceUrl: 'https://stylelint.io/',
  },
};
