// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';

export const ariaRolesTopics: Record<string, ContentTopic> = {
  'html-aria-role-types': {
    id: 'html-aria-role-types',
    heading: 'ARIA role types',
    blocks: [
      {
        type: 'paragraph',
        text: 'There are 6 categories of ARIA roles:',
      },
      {
        type: 'subheading',
        level: 3,
        text: '1. Document structure roles',
      },
      {
        type: 'paragraph',
        text: 'Document Structure roles are used to provide a structural description for a section of content. Most of these roles should no longer be used as browsers now support semantic HTML elements with the same meaning. The roles without HTML equivalents, such as presentation, toolbar and tooltip roles, provide information on the document structure to assistive technologies such as screen readers as equivalent native HTML tags are not available.',
      },
      {
        type: 'list',
        ordered: false,
        items: ['`toolbar`', '`tooltip`', '`feed`', '`math`', '`presentation` / `none`', '`note`'],
      },
      {
        type: 'paragraph',
        text: 'For most document structure roles, semantic HTML equivalent elements are available and supported. Avoid using:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          '`application`',
          '`article` (use article)',
          '`cell` (use td)',
          '`columnheader` (use <th scope="col">)',
          '`definition` (use dfn)',
          '`directory`',
          '`document`',
          '`figure` (use figure instead)',
          '`group`',
          '`heading` (use h1 through h6)',
          '`img` (use img or picture instead)',
          '`list` (use either ul or ol instead)',
          '`listitem` (use li instead)',
          '`meter` (use meter instead)',
          '`row` (use the tr with table)',
          '`rowgroup` (use thead, tfoot and tbody)',
          '`rowheader` (use <th scope="row">)',
          "`separator` (use hr if it doesn't have focus)",
          '`table` (use table)',
          '`term` (use dfn)',
        ],
      },
      {
        type: 'paragraph',
        text: 'These are included for completeness, but in most cases are rarely, if ever, useful:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          '`associationlist`',
          '`associationlistitemkey`',
          '`associationlistitemvalue`',
          '`blockquote`',
          '`caption`',
          '`code`',
          '`deletion`',
          '`emphasis`',
          '`insertion`',
          '`paragraph`',
          '`strong`',
          '`subscript`',
          '`superscript`',
          '`time`',
        ],
      },
      {
        type: 'subheading',
        level: 3,
        text: '2. Widget roles',
      },
      {
        type: 'paragraph',
        text: 'Widget roles are used to define common interactive patterns. Like document structure roles, some widget roles have the same semantics as well-supported native HTML elements, and therefore should be avoided. The key difference is that widget roles typically require JavaScript for interaction, while document structure roles often do not.',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          '`scrollbar`',
          '`searchbox`',
          '`separator` (when focusable)',
          '`slider`',
          '`spinbutton`',
          '`switch`',
          '`tab`',
          '`tabpanel`',
          '`treeitem`',
        ],
      },
      {
        type: 'paragraph',
        text: "Avoid using `button`, `checkbox`, `gridcell`, `link`, `menuitem`, `menuitemcheckbox`, `menuitemradio`, `option`, `progressbar`, `radio`, and `textbox`, which we've included for completeness. For most, semantic equivalents with accessible interactivity are available and supported. See the individual role documentation for more information.",
      },
      {
        type: 'subheading',
        level: 4,
        text: 'Composite widget roles',
      },
      {
        type: 'list',
        ordered: false,
        items: ['`combobox`', '`menu`', '`menubar`', '`tablist`', '`tree`', '`treegrid`'],
      },
      {
        type: 'paragraph',
        text: "Avoid using `grid`, `listbox`, and `radiogroup`, which we've included for completeness. See the individual role documentation for more information.",
      },
      {
        type: 'paragraph',
        text: 'Note that there is also a widget role (`role="widget"`), which is an abstract role and not in the widget role category.',
      },
      {
        type: 'subheading',
        level: 3,
        text: '3. Landmark roles',
      },
      {
        type: 'paragraph',
        text: 'Landmark roles provide a way to identify the organization and structure of a web page. By classifying and labeling sections of a page, structural information conveyed visually through layout is represented programmatically. Screen readers use landmark roles to provide keyboard navigation to important sections of a page. Use these sparingly. Too many landmark roles create "noise" in screen readers, making it difficult to understand the overall layout of the page.',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          '`banner` (document header)',
          '`complementary` (aside)',
          '`contentinfo` (document footer)',
          '`form` (form)',
          '`main` (main)',
          '`navigation` (nav)',
          '`region` (section)',
          '`search` (search)',
        ],
      },
      {
        type: 'subheading',
        level: 3,
        text: '4. Live region roles',
      },
      {
        type: 'paragraph',
        text: 'Live Region roles are used to define elements with content that will be dynamically changed. Sighted users can see dynamic changes when they are visually noticeable. These roles help low vision and blind users know if content has been updated. Assistive technologies, like screen readers, can be made to announce dynamic content changes:',
      },
      {
        type: 'list',
        ordered: false,
        items: ['`alert`', '`log`', '`marquee`', '`status`', '`timer`'],
      },
      {
        type: 'subheading',
        level: 3,
        text: '5. Window roles',
      },
      {
        type: 'paragraph',
        text: 'Window roles define sub-windows to the main document window, within the same window, such as pop up modal dialogs:',
      },
      {
        type: 'list',
        ordered: false,
        items: ['`alertdialog`', '`dialog`'],
      },
      {
        type: 'subheading',
        level: 3,
        text: '6. Abstract roles',
      },
      {
        type: 'paragraph',
        text: 'Abstract roles are only intended for use by browsers to help organize and streamline a document. They should not be used by developers writing HTML markup. Doing so will not result in any meaningful information being conveyed to assistive technologies or to users.',
      },
      {
        type: 'paragraph',
        text: 'Avoid using `command`, `composite`, `input`, `landmark`, `range`, `roletype`, `section`, `sectionhead`, `select`, `structure`, `widget`, and `window`.',
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: "Don't use abstract roles in your sites and applications. They are for use by browsers. They are included for reference only.",
        },
      },
      {
        type: 'callout',
        callout: {
          variant: 'warning',
          title: 'Warning',
          body: '"Abstract roles are used for the ontology. Authors MUST NOT use abstract roles in content." - The WAI-ARIA specification',
        },
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles',
  },
};
