// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';
import grumpyCatSmall from '../../assets/html/grumpy-cat-small.png';
import grumpyCatAttributeSmall from '../../assets/html/grumpy-cat-attribute-small.png';

export const basicHtmlSyntaxTopics: Record<string, ContentTopic> = {
  'html-what-is-html': {
    id: 'html-what-is-html',
    heading: 'What is HTML?',
    blocks: [
      {
        type: 'paragraph',
        text: 'HTML (HyperText Markup Language) is a markup language that tells web browsers how to structure the web pages you visit. HTML consists of a series of elements, which you use to enclose, wrap, or mark up different parts of content to make it appear or act in a certain way. The enclosing tags can make content into a hyperlink to link to another page, italicize words, and so on. For example, consider the following line of text:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'plain',
          code: 'My cat is very grumpy',
        },
      },
      {
        type: 'paragraph',
        text: 'We could specify that this text is a paragraph by enclosing it in paragraph (`<p>`) tags:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p>My cat is very grumpy</p>',
        },
      },
      {
        type: 'paragraph',
        text: 'Or, we could specify that this text is a top-level heading by enclosing it in `<h1>` tags:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<h1>My cat is very grumpy</h1>',
        },
      },
      {
        type: 'paragraph',
        text: "HTML lives inside text files called HTML documents, or just documents, with a `.html` file extension. Where previously we've talked about web pages, an HTML document contains the web page's content and specifies its structure.",
      },
      {
        type: 'paragraph',
        text: "The most common HTML file you'll encounter is `index.html`, which is generally used to contain a website's home page content. It's also common to see subfolders containing their own `index.html` files, so a website can have multiple index files in different places.",
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'Tags in HTML are not case-sensitive. This means they can be written in uppercase or lowercase. For example, a `<title>` tag could be written as `<title>`, `<TITLE>`, `<Title>`, `<TiTlE>`, etc., and it will work. However, it is best practice to write all tags in lowercase for consistency and readability.',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/Basic_HTML_syntax',
  },
  'html-anatomy-of-an-html-element': {
    id: 'html-anatomy-of-an-html-element',
    heading: 'Anatomy of an HTML element',
    blocks: [
      {
        type: 'paragraph',
        text: "Let's further explore our paragraph element from the previous section:",
      },
      {
        type: 'image',
        src: grumpyCatSmall,
        alt: 'A sample code snippet demonstrating the structure of an html element.<p> My cat is very grumpy </p>.',
      },
      {
        type: 'paragraph',
        text: 'Our complete element consists of:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'The opening tag: This consists of the name of the element (in this example, p for paragraph), wrapped in opening and closing angle brackets. This opening tag marks where the element begins or starts to take effect. In this example, it precedes the start of the paragraph text.',
          'The content: This is the content of the element. In this example, it is the paragraph text — "My cat is very grumpy".',
          'The closing tag: This is the same as the opening tag, except that it includes a forward slash before the element name. This marks where the element ends. Failing to include a closing tag is a common beginner error that can produce peculiar results.',
        ],
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Nesting elements',
      },
      {
        type: 'paragraph',
        text: 'Elements can be placed within other elements. This is called nesting. If we wanted to state that our cat is very grumpy, we could wrap the word very in a `<strong>` element, which gives the word strong(er) text formatting:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p>My cat is <strong>very</strong> grumpy.</p>',
        },
      },
      {
        type: 'paragraph',
        text: 'In this code block, the text "My cat is very grumpy." is all defined as a paragraph. The word "very" is additionally defined as having strong importance.',
      },
      {
        type: 'paragraph',
        text: 'There is a right and wrong way to do nesting. In the code block above, we open the `<p>` element first, then open the `<strong>` element. For proper nesting, we close the `<strong>` element first, then close the `<p>`.',
      },
      {
        type: 'paragraph',
        text: 'The following is an example of the wrong way to do nesting:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p>My cat is <strong>very grumpy.</p></strong>',
        },
      },
      {
        type: 'paragraph',
        text: 'The tags have to open and close so that they are inside or outside one another. Because the elements overlap in the previous code block, the browser has to guess at your intent. This kind of guessing can result in unexpected results.',
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Void elements',
      },
      {
        type: 'paragraph',
        text: 'Not all elements follow the pattern of an opening tag, content, then a closing tag. Some elements consist of a single tag, which is typically used to insert/embed something in the document. Such elements are called void elements, which means "elements that cannot contain other HTML content".',
      },
      {
        type: 'paragraph',
        text: 'For example, the `<br>` element inserts a line break into a line of text, which causes it to break onto multiple lines:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p>\n  This is a single paragraph, but we are going to <br />break it onto two lines.\n</p>',
        },
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: "In some HTML examples, you'll see a `/` added at the end of a void element's tag, for example `<br />`. This is a different style of markup syntax, which isn't wrong, but this \"closing slash\" is not needed.",
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/Basic_HTML_syntax',
  },
  'html-attributes': {
    id: 'html-attributes',
    heading: 'Attributes',
    blocks: [
      {
        type: 'paragraph',
        text: 'Elements can also have attributes. Attributes look like this:',
      },
      {
        type: 'image',
        src: grumpyCatAttributeSmall,
        alt: 'paragraph tag with \'class="editor-note"\' attribute emphasized',
      },
      {
        type: 'paragraph',
        text: "Attributes contain extra information about the element that isn't part of its content. The `class` attribute provides an identifying name that can be used to target the element with styles (CSS) or scripting information (JavaScript).",
      },
      {
        type: 'paragraph',
        text: 'An attribute should have:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'A space between it and the element name. When an element has more than one attribute, the attributes should be separated by spaces too.',
          'The attribute name, followed by an equals sign (`=`).',
          'An attribute value, wrapped with opening and closing quote marks.',
        ],
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Adding attributes to an element',
      },
      {
        type: 'paragraph',
        text: "Now it's your turn again. In this section you are going to explore the `<img>` element, which is used to display an image on the page. The `<img>` element can take several attributes, including:",
      },
      {
        type: 'list',
        ordered: false,
        items: [
          '`src`: A required attribute that specifies the URL (web address) of the image. For example: `src="https://mdn.github.io/shared-assets/images/examples/fx-nightly-512.png"`.',
          '`alt`: Specifies a text description to describe the image to people who cannot see it. For example: `alt="The Firefox Nightly icon"`. This attribute is not technically required, but you really should provide a text description for all images that convey meaning (as opposed to being purely decorative).',
          '`width`: Specifies the width of the image in pixels. For example: `width="300"`.',
          '`height`: Specifies the height of the image in pixels. For example: `height="300"`.',
        ],
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Boolean attributes',
      },
      {
        type: 'paragraph',
        text: 'Sometimes you will see HTML attributes written without values. These are called Boolean attributes. When a boolean attribute is added, its value is set to `true`, irrespective of whatever value is assigned to it (even no value). If an attribute is not included in an HTML tag, its value is set to `false`.',
      },
      {
        type: 'paragraph',
        text: 'For example, consider the `disabled` attribute, which you can assign to form `<input>` elements to stop the user entering data into them. For example:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<label for="first-input">This input is disabled</label>\n<input id="first-input" type="text" disabled="disabled" />\n<br />',
        },
      },
      {
        type: 'paragraph',
        text: 'As shorthand, it is acceptable to write the `disabled` attribute without a value:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<label for="second-input">This input is also disabled</label>\n<input id="second-input" type="text" disabled />\n<br />',
        },
      },
      {
        type: 'paragraph',
        text: "For reference, let's also provide a non-disabled `<input>` element so you can compare and contrast (note how the `disabled` inputs are somewhat grayed out in the below rendering):",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<label for="third-input">This input isn\'t disabled; you can type into it</label>\n<input id="third-input" type="text" />',
        },
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'The `<label>` elements included in the above code provide a way to associate descriptive labels with form elements. We included them because it is a best practice, and to provide some separation between the form inputs.',
        },
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Omitting quotes around attribute values',
      },
      {
        type: 'paragraph',
        text: "It is OK to omit the quotes from around attribute values in certain circumstances. But because this can break your markup in other circumstances, we advise you to always include the quote marks. Let's explore why.",
      },
      {
        type: 'paragraph',
        text: 'The element in the code snippet below, `<a>`, is called an anchor. Anchors enclose text and turn them into links. The `href` attribute specifies the URL the link points to. You can omit the quotes around the `href` attribute value shown below without any negative consequences, because it has no spaces in it:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<a href=https://www.mozilla.org/>favorite website</a>',
        },
      },
      {
        type: 'paragraph',
        text: 'However, you soon run into problems when omitting quotes from attribute values with spaces. Consider the `title` attribute shown below, which provides a description of the linked page ("The Mozilla homepage") that should appear as a tooltip when the link is hovered over by a mouse pointer.',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<a href=https://www.mozilla.org/ title=The Mozilla homepage>favorite website</a>',
        },
      },
      {
        type: 'paragraph',
        text: 'Because quotes are not included around the `title` attribute value, the browser interprets it as three attributes: a `title` attribute with the value `The`, and two Boolean attributes — `Mozilla` and `homepage`. Obviously, this is not what we intended! If you\'re using a device with a mouse pointer, you can try hovering over the link to view the title tooltip (it will give you "The" rather than the intended "The Mozilla homepage").',
      },
      {
        type: 'paragraph',
        text: 'Always include quotes around attribute values. It avoids errors and unintended behavior, and results in more readable code.',
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Single or double quotes?',
      },
      {
        type: 'paragraph',
        text: 'In this article, we have wrapped all our attribute values in double quotes. However, you might see single quotes used in some HTML code. This is a matter of style. You can feel free to choose which one you prefer. Both of these lines are equivalent:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<a href=\'https://www.example.com\'>A link to my example.</a>\n\n<a href="https://www.example.com">A link to my example.</a>',
        },
      },
      {
        type: 'paragraph',
        text: "Make sure you don't mix single quotes and double quotes. The below example mixes quotes, which will lead to errors because as far as the browser is concerned, the `href` attribute value has not been finished:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<a href="https://www.example.com\'>A link to my example.</a>',
        },
      },
      {
        type: 'paragraph',
        text: 'If you use one type of quote, you can include the other type of quote inside your attribute values. This works fine:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<a href="https://www.example.com" title="Isn\'t this fun?">\n  A link to my example.\n</a>',
        },
      },
      {
        type: 'paragraph',
        text: 'To use quote marks inside other quote marks of the same type (single quote or double quote), you can use character references. For example, this will break:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<a href="https://www.example.com" title="An "interesting" reference">A link to my example.</a>',
        },
      },
      {
        type: 'paragraph',
        text: 'Instead, you need to do this:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<a href="https://www.example.com" title="An &quot;interesting&quot; reference">A link to my example.</a>',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/Basic_HTML_syntax',
  },
  'html-anatomy-of-an-html-document': {
    id: 'html-anatomy-of-an-html-document',
    heading: 'Anatomy of an HTML document',
    blocks: [
      {
        type: 'paragraph',
        text: "Individual HTML elements aren't very useful on their own. Next, let's examine how individual elements combine to form an entire HTML page.",
      },
      {
        type: 'paragraph',
        text: 'The following example is a very simple complete webpage:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<!doctype html>\n<html lang="en-US">\n  <head>\n    <meta charset="utf-8" />\n    <title>My test page</title>\n  </head>\n  <body>\n    <p>This is my page</p>\n  </body>\n</html>',
        },
      },
      {
        type: 'paragraph',
        text: 'The parts of this example are as follows:',
      },
      {
        type: 'list',
        ordered: true,
        items: [
          '`<!doctype html>`: The doctype. When HTML was young (1991-1992), doctypes were meant to act as links to a set of rules that the HTML page had to follow to be considered good HTML. Doctypes used to look something like this:',
        ],
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<!doctype html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">',
        },
      },
      {
        type: 'paragraph',
        text: 'In modern times, the doctype is a historical artifact that needs to be included for everything else to work correctly. `<!doctype html>` is the shortest string of characters that counts as a valid doctype, and it should be included at the top of all webpages. That is all you need to know!',
      },
      {
        type: 'list',
        ordered: true,
        start: 2,
        items: [
          '`<html></html>`: The `<html>` element. This element wraps all the content on the page. It is sometimes known as the root element.',
          "`<head></head>`: The `<head>` element. This element acts as a container for information about the page that isn't part of the content that users will see. This can include keywords and a page description to be shown in search results, CSS to style content, character set declarations, and more. You will learn more about the head of the page in the next article.",
          '`<meta charset="utf-8">`: A `<meta>` element. This element represents metadata that describes the page. The `charset` attribute specifies the character encoding your document will use. UTF-8 includes most characters from the vast majority of human written languages, which means the page will be able to display different languages successfully. There is no reason not to set this, and it can help avoid some problems later.',
          '`<title></title>`: The `<title>` element. This sets the title of the page, which is the title that appears in the browser tab the page is loaded in. The page title is also used to describe the page when it is bookmarked.',
          '`<body></body>`: The `<body>` element. This contains all the content that displays on the page, including text, images, videos, games, playable audio tracks, and so on.',
        ],
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/Basic_HTML_syntax',
  },
  'html-whitespace-in-html': {
    id: 'html-whitespace-in-html',
    heading: 'Whitespace in HTML',
    blocks: [
      {
        type: 'paragraph',
        text: "In previous examples, we've included lot of whitespace in the code. In most cases this is completely optional, and included mainly to make the code more readable. For example, these two code snippets are equivalent:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p id="noWhitespace">Dogs are silly.</p>\n\n<p id="whitespace">Dogs\n    are\n        silly.</p>',
        },
      },
      {
        type: 'paragraph',
        text: 'In almost all elements (there are exceptions such as `<pre>`), no matter how much whitespace you use inside HTML element content, the HTML parser reduces each sequence of whitespace to a single space when rendering the code.',
      },
      {
        type: 'paragraph',
        text: 'It is up to you to choose a preferred code formatting style. It is common to give each nested element two spaces of indentation more than the one it is sitting inside; this is the style we use on MDN.',
      },
      {
        type: 'paragraph',
        text: 'For example:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<section>\n  <div>\n    <p>A paragraph of content.</p>\n  </div>\n</section>',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/Basic_HTML_syntax',
  },
  'html-character-references-including-special-characters-in-html': {
    id: 'html-character-references-including-special-characters-in-html',
    heading: 'Character references: including special characters in HTML',
    blocks: [
      {
        type: 'paragraph',
        text: 'In HTML, the characters `<`, `>`, `"`, `\'`, and `&` are special characters. They are parts of the HTML syntax itself. So how do you include these special characters in your text? For example, how can you use a literal ampersand or less-than sign in your content without it being interpreted as code?',
      },
      {
        type: 'paragraph',
        text: 'You do this with character references. These are special codes that represent characters, to be used in these exact circumstances. Each character reference starts with an ampersand (&), and ends with a semicolon (;).',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          '`<` is written as `&lt;`',
          '`>` is written as `&gt;`',
          '`"` is written as `&quot;`',
          "`'` is written as `&apos;`",
          '`&` is written as `&amp;`',
        ],
      },
      {
        type: 'paragraph',
        text: 'Character references are fairly easily remembered because the text they use is an abbreviation of the character name — for example "lt" = "less than", "quot" = "quotation", and "amp" = "ampersand". To learn more about entity references, see List of XML and HTML character entity references (Wikipedia).',
      },
      {
        type: 'paragraph',
        text: 'In the example below, there are two paragraphs:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<p>In HTML, you define a paragraph using the <p> element.</p>\n\n<p>In HTML, you define a paragraph using the &lt;p&gt; element.</p>',
        },
      },
      {
        type: 'paragraph',
        text: 'You can see that the first paragraph has gone wrong, because the browser has interpreted the second instance of `<p>` as starting a new paragraph. The second paragraph renders fine because the angle brackets of the content "&lt;p&gt;" are represented by character references.',
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: "You don't need to use entity references for any other symbols, as modern browsers will handle the actual symbols just fine as long as your HTML's character encoding is set to UTF-8.",
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/Basic_HTML_syntax',
  },
  'html-html-comments': {
    id: 'html-html-comments',
    heading: 'HTML comments',
    blocks: [
      {
        type: 'paragraph',
        text: "HTML has a mechanism to write comments in the code. Browsers ignore comments, therefore they are invisible to the user. The purpose of comments is to allow you to include notes in the code to explain how it works. This is very useful if you return to a code base after being away for long enough that you don't remember it, or if someone else starts working on it that has never seen it before.",
      },
      {
        type: 'paragraph',
        text: 'To write an HTML comment, wrap it in the special markers `<!--` and `-->`, as shown below:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: "<p>I'm not inside a comment</p>\n\n<!-- <p>I am!</p> -->",
        },
      },
      {
        type: 'paragraph',
        text: 'Only the first paragraph is displayed in the live output; the second line is not rendered because it is an HTML comment.',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/Basic_HTML_syntax',
  },
};
