// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';
import simpleVideo from '../../assets/html/simple-video.png';
import containersandtracks from '../../assets/html/containersandtracks.png';
import posterScreenshotUpdated from '../../assets/html/poster_screenshot_updated.png';
import audioPlayer from '../../assets/html/audio-player.png';

export const htmlVideoAndAudioTopics: Record<string, ContentTopic> = {
  'html-video-and-audio-video-and-audio-on-the-web': {
    id: 'html-video-and-audio-video-and-audio-on-the-web',
    heading: 'Video and audio on the web',
    blocks: [
      {
        type: 'paragraph',
        text: "The first influx of online videos and audio were made possible by proprietary plugin-based technologies like Flash and Silverlight. Both of these had security and accessibility issues, and are now obsolete, in favor of native HTML solutions `<video>` and `<audio>` elements and the availability of JavaScript APIs for controlling them. We'll not be looking at JavaScript here — just the basic foundations that can be achieved with HTML.",
      },
      {
        type: 'paragraph',
        text: "We won't be teaching you how to produce audio and video files — that requires a completely different skill set. We have provided you with sample audio and video files and example code for your own experimentation, in case you are unable to get hold of your own.",
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: "Before you begin here, you should also know that there are quite a few OVPs (online video providers) like YouTube, Dailymotion, and Vimeo, and online audio providers like Soundcloud. Such companies offer a convenient, easy way to host and consume videos, so you don't have to worry about the enormous bandwidth consumption. OVPs even usually offer ready-made code for embedding video/audio in your webpages; if you use that route, you can avoid some of the difficulties we discuss in this article. We'll be discussing this kind of service a bit more in the next article.",
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/HTML_video_and_audio',
  },
  'html-video-and-audio-the-video-element': {
    id: 'html-video-and-audio-the-video-element',
    heading: 'The \\<video> element',
    blocks: [
      {
        type: 'paragraph',
        text: 'The `<video>` element allows you to embed a video very easily. A really simple example looks like this:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<video src="rabbit320.webm" controls>\n  <p>\n    Your browser doesn\'t support HTML video. Here is a\n    <a href="rabbit320.webm">link to the video</a> instead.\n  </p>\n</video>',
        },
      },
      {
        type: 'paragraph',
        text: 'The features to note are:',
      },
      {
        type: 'definitions',
        items: [
          {
            term: '`src`',
            description:
              'In the same way as for the `<img>` element, the `src` (source) attribute contains a path to the video you want to embed. It works in exactly the same way.',
          },
          {
            term: '`controls`',
            description:
              "Users must be able to control video and audio playback (it's especially critical for people who have epilepsy.) You must either use the `controls` attribute to include the browser's own control interface, or build your interface using the appropriate JavaScript API. At a minimum, the interface must include a way to start and stop the media, and to adjust the volume.",
          },
          {
            term: 'The paragraph inside the `<video>` tags',
            description:
              "This is called fallback content — this will be displayed if the browser accessing the page doesn't support the `<video>` element, allowing us to provide a fallback for older browsers. This can be anything you like; in this case, we've provided a direct link to the video file, so the user can at least access it some way regardless of what browser they are using.",
          },
        ],
      },
      {
        type: 'paragraph',
        text: 'The embedded video will look something like this:',
      },
      {
        type: 'image',
        src: simpleVideo,
        alt: 'A simple video player showing a video of a small white rabbit',
      },
      {
        type: 'paragraph',
        text: 'You can try the example live here (see also the source code.)',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/HTML_video_and_audio',
  },
  'html-video-and-audio-using-multiple-source-formats-to-improve-compatibility': {
    id: 'html-video-and-audio-using-multiple-source-formats-to-improve-compatibility',
    heading: 'Using multiple source formats to improve compatibility',
    blocks: [
      {
        type: 'paragraph',
        text: "There's a problem with the above example. It is possible that the video might not play for you, because different browsers support different video (and audio) formats. Fortunately, there are things you can do to help prevent this from being an issue.",
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Contents of a media file',
      },
      {
        type: 'paragraph',
        text: "First, let's go through the terminology quickly. Formats like OGG, WAV, MP4 and WebM are called container formats. They define a structure in which the audio and/or video tracks that make up the media are stored, along with metadata describing the media, what codecs are used to encode its channels, and so forth.",
      },
      {
        type: 'paragraph',
        text: 'A WebM file containing a movie which has a main video track and one alternate angle track, plus audio for both English and Spanish, in addition to audio for an English commentary track can be conceptualized as shown in the diagram below. Also included are text tracks containing closed captions for the feature film, Spanish subtitles for the film, and English captions for the commentary.',
      },
      {
        type: 'image',
        src: containersandtracks,
        alt: 'Diagram conceptualizing the contents of a media file at the track level.',
      },
      {
        type: 'paragraph',
        text: 'The audio and video tracks within the container hold data in the appropriate format for the codec used to encode that media. Different formats are used for audio tracks versus video tracks. Each audio track is encoded using an audio codec, while video tracks are encoded using (as you probably have guessed) a video codec. As we talked about before, different browsers support different video and audio formats, and different container formats (like OGG, MP4, and WebM, which in turn can contain different types of video and audio).',
      },
      {
        type: 'paragraph',
        text: 'For example:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          'A WebM container typically packages Vorbis or Opus audio with VP8/VP9 video. This is supported in all modern browsers, though older versions may not work.',
          'An MP4 container often packages AAC or MP3 audio with H.264 video. This is also supported in all modern browsers.',
          'The Ogg container tends to use Vorbis audio and Theora video. This is best supported in Firefox and Chrome, but has basically been superseded by the better quality WebM format.',
        ],
      },
      {
        type: 'paragraph',
        text: "There are some special cases. For example, for some types of audio, a codec's data is often stored without a container, or with a simplified container. One such instance is the FLAC codec, which is stored most commonly in FLAC files, which are just raw FLAC tracks.",
      },
      {
        type: 'paragraph',
        text: 'Another example is the ever-popular "MP3 file". An "MP3 file" is an audio file encoded using MPEG-1 Audio Layer III compression. While it can include metadata, it is not encapsulated within a separate MPEG or MPEG-2 container. Its widespread support in the `<audio>` and `<video>` elements is largely a testament to its enduring popularity.',
      },
      {
        type: 'paragraph',
        text: "An audio player will tend to play an audio track directly, e.g., an MP3 or Ogg file. These don't need containers.",
      },
      {
        type: 'subheading',
        level: 3,
        text: 'Media file support in browsers',
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: "Several popular formats, such as MP3 and MP4/H.264, are excellent but are encumbered by patents; that is, there are patents covering some or all of the technology that they're based upon. In the United States, patents covered MP3 until 2017, and H.264 is encumbered by patents through at least 2027. Because of those patents, browsers that wish to implement support for those codecs must pay typically enormous license fees. In addition, some people prefer to avoid restricted software and prefer to use only open formats. Due to these legal and preferential reasons, web developers find themselves having to support multiple formats to provide a video experience to their entire audience.",
        },
      },
      {
        type: 'paragraph',
        text: 'The codecs described in the previous section exist to compress video and audio into manageable files, since raw audio and video are both exceedingly large. Each web browser supports an assortment of codecs, like Vorbis or H.264, which are used to convert the compressed audio and video into binary data and back. Each codec offers its own advantages and drawbacks, and each container may also offer its own positive and negative features affecting your decisions about which to use.',
      },
      {
        type: 'paragraph',
        text: "Things become slightly more complicated because not only does each browser support a different set of container file formats, they also each support a different selection of codecs. In order to maximize the likelihood that your website or app will work on a user's browser, you may need to provide each media file you use in multiple formats. If your site and the user's browser don't share a media format in common, your media won't play.",
      },
      {
        type: 'paragraph',
        text: "Due to the intricacies of ensuring your app's media is viewable across every combination of browsers, platforms, and devices you wish to reach, choosing the best combination of codecs and container can be a complicated task. See Choosing the right container for help selecting the container file format best suited for your needs; similarly, see Choosing a video codec and Choosing an audio codec for help selecting the first media codecs to use for your content and your target audience.",
      },
      {
        type: 'paragraph',
        text: "One additional thing to keep in mind: mobile browsers may support additional formats not supported by their desktop equivalents, just like they may not support all the same formats the desktop version does. On top of that, both desktop and mobile browsers may be designed to offload handling of media playback (either for all media or only for specific types it can't handle internally). This means media support is partly dependent on what software the user has installed.",
      },
      {
        type: 'paragraph',
        text: 'So how do we do this? Take a look at the following updated example (try it live here, also):',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<video controls>\n  <source src="rabbit320.mp4" type="video/mp4" />\n  <source src="rabbit320.webm" type="video/webm" />\n  <p>\n    Your browser doesn\'t support this video. Here is a\n    <a href="rabbit320.mp4">link to the video</a> instead.\n  </p>\n</video>',
        },
      },
      {
        type: 'paragraph',
        text: "Here we've taken the `src` attribute out of the actual `<video>` tag, and instead included separate `<source>` elements that point to their own sources. In this case the browser will go through the `<source>` elements and play the first one that it has the codec to support. Including WebM and MP4 sources should be enough to play your video on most platforms and browsers these days.",
      },
      {
        type: 'paragraph',
        text: "Each `<source>` element also has a `type` attribute. This is optional, but it is advised that you include it. The `type` attribute contains the MIME type of the file specified by the `<source>`, and browsers can use the `type` to immediately skip videos they don't understand. If `type` isn't included, browsers will load and try to play each file until they find one that works, which obviously takes time and is an unnecessary use of resources.",
      },
      {
        type: 'paragraph',
        text: 'Refer to our guide to media types and formats for help selecting the best containers and codecs for your needs, as well as to look up the right MIME types to specify for each.',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/HTML_video_and_audio',
  },
  'html-video-and-audio-other-video-features': {
    id: 'html-video-and-audio-other-video-features',
    heading: 'Other \\<video> features',
    blocks: [
      {
        type: 'paragraph',
        text: 'There are a number of other features you can include when displaying an HTML video. Take a look at our next example:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<video\n  controls\n  width="400"\n  height="400"\n  autoplay\n  loop\n  muted\n  preload="auto"\n  poster="poster.png">\n  <source src="rabbit320.mp4" type="video/mp4" />\n  <source src="rabbit320.webm" type="video/webm" />\n  <p>\n    Your browser doesn\'t support this video. Here is a\n    <a href="rabbit320.mp4">link to the video</a> instead.\n  </p>\n</video>',
        },
      },
      {
        type: 'paragraph',
        text: 'The resulting UI looks something like this:',
      },
      {
        type: 'image',
        src: posterScreenshotUpdated,
        alt: 'A video player showing a poster image before it plays. The poster image says HTML video example, OMG hell yeah!',
      },
      {
        type: 'paragraph',
        text: 'Features include:',
      },
      {
        type: 'definitions',
        items: [
          {
            term: '`width` and `height`',
            description:
              'You can control the video size either with these attributes or with CSS. In both cases, videos maintain their native width-height ratio — known as the aspect ratio. If the aspect ratio is not maintained by the sizes you set, the video will grow to fill the space horizontally, and the unfilled space will just be given a solid background color by default.',
          },
          {
            term: '`autoplay`',
            description:
              'Makes the audio or video start playing right away, while the rest of the page is loading. You are advised not to use autoplaying video (or audio) on your sites, because users can find it really annoying.',
          },
          {
            term: '`loop`',
            description:
              'Makes the video (or audio) start playing again whenever it finishes. This can also be annoying, so only use if really necessary.',
          },
          {
            term: '`muted`',
            description: 'Causes the media to play with the sound turned off by default.',
          },
          {
            term: '`poster`',
            description:
              'The URL of an image which will be displayed before the video is played. It is intended to be used for a splash screen or advertising screen.',
          },
          {
            term: '`preload`',
            description:
              'Used for buffering large files; it can take one of three values: `"none"` does not buffer the file `"auto"` buffers the media file `"metadata"` buffers only the metadata for the file',
          },
        ],
      },
      {
        type: 'paragraph',
        text: "You can find the above example available to play live on GitHub (also see the source code.) Note that we haven't included the `autoplay` attribute in the live version — if the video starts to play as soon as the page loads, you don't get to see the poster!",
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/HTML_video_and_audio',
  },
  'html-video-and-audio-the-audio-element': {
    id: 'html-video-and-audio-the-audio-element',
    heading: 'The \\<audio> element',
    blocks: [
      {
        type: 'paragraph',
        text: 'The `<audio>` element works just like the `<video>` element, with a few small differences as outlined below. A typical example might look like so:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<audio controls>\n  <source src="viper.mp3" type="audio/mp3" />\n  <source src="viper.ogg" type="audio/ogg" />\n  <p>\n    Your browser doesn\'t support this audio file. Here is a\n    <a href="viper.mp3">link to the audio</a> instead.\n  </p>\n</audio>',
        },
      },
      {
        type: 'paragraph',
        text: 'This produces something like the following in a browser:',
      },
      {
        type: 'image',
        src: audioPlayer,
        alt: 'A simple audio player with a play button, timer, volume control, and progress bar',
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'You can run the audio demo live on GitHub (also see the audio player source code.)',
        },
      },
      {
        type: 'paragraph',
        text: 'This takes up less space than a video player, as there is no visual component — you just need to display controls to play the audio. Other differences from HTML video are as follows:',
      },
      {
        type: 'list',
        ordered: false,
        items: [
          "The `<audio>` element doesn't support the `width`/`height` attributes — again, there is no visual component, so there is nothing to assign a width or height to.",
          "It also doesn't support the `poster` attribute — again, no visual component.",
        ],
      },
      {
        type: 'paragraph',
        text: 'Other than this, `<audio>` supports all the same features as `<video>` — review the above sections for more information about them.',
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/HTML_video_and_audio',
  },
  'html-video-and-audio-displaying-video-text-tracks': {
    id: 'html-video-and-audio-displaying-video-text-tracks',
    heading: 'Displaying video text tracks',
    blocks: [
      {
        type: 'paragraph',
        text: "Now we'll discuss a slightly more advanced concept that is really useful to know about. Many people can't or don't want to hear the audio/video content they find on the Web, at least at certain times. For example:",
      },
      {
        type: 'list',
        ordered: false,
        items: [
          "Many people have auditory impairments (such as being hard of hearing or deaf) so can't hear the audio clearly if at all.",
          'Others may not be able to hear the audio because they are in noisy environments (like a crowded bar when a sports game is being shown).',
          'Similarly, in environments where having the audio playing would be a distraction or disruption (such as in a library or when a partner is trying to sleep), having captions can be very useful.',
          "People who don't speak the language of the video might want a text transcript or even translation to help them understand the media content.",
        ],
      },
      {
        type: 'paragraph',
        text: "Wouldn't it be nice to be able to provide these people with a transcript of the words being spoken in the audio/video? Well, thanks to HTML video, you can. To do so we use the WebVTT file format and the `<track>` element.",
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: '"Transcribe" means "to write down spoken words as text." The resulting text is a "transcript."',
        },
      },
      {
        type: 'paragraph',
        text: 'WebVTT is a format for writing text files containing multiple strings of text along with metadata such as the time in the video at which each text string should be displayed, and even limited styling/positioning information. These text strings are called cues, and there are several kinds of cues which are used for different purposes. The most common cues are:',
      },
      {
        type: 'definitions',
        items: [
          {
            term: 'subtitles',
            description:
              "Translations of foreign material, for people who don't understand the words spoken in the audio.",
          },
          {
            term: 'captions',
            description:
              "Synchronized transcriptions of dialog or descriptions of significant sounds, to let people who can't hear the audio understand what is going on.",
          },
          {
            term: 'timed descriptions',
            description:
              'Text which should be spoken by the media player in order to describe important visuals to blind or otherwise visually impaired users.',
          },
        ],
      },
      {
        type: 'paragraph',
        text: 'A typical WebVTT file will look something like this:',
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'plain',
          code: 'WEBVTT\n\n1\n00:00:22.230 --> 00:00:24.606\nThis is the first subtitle.\n\n2\n00:00:30.739 --> 00:00:34.074\nThis is the second.\n\n…',
        },
      },
      {
        type: 'paragraph',
        text: 'To get this displayed along with the HTML media playback, you need to:',
      },
      {
        type: 'list',
        ordered: true,
        items: [
          'Save it as a `.vtt` file somewhere the server can serve (see below), such as in the same directory as the HTML file.',
          'Link to the `.vtt` file with the `<track>` element. `<track>` should be placed within `<audio>` or `<video>`, but after all `<source>` elements. Use the `kind` attribute to specify whether the cues are `subtitles`, `captions`, or `descriptions`. Further, use `srclang` to tell the browser what language you have written the subtitles in. Finally, add `label` to help readers identify the language they are searching for.',
        ],
      },
      {
        type: 'paragraph',
        text: "Here's an example:",
      },
      {
        type: 'code',
        code: {
          filename: '',
          language: 'html',
          code: '<video controls>\n  <source src="example.mp4" type="video/mp4" />\n  <source src="example.webm" type="video/webm" />\n  <track kind="subtitles" src="subtitles_es.vtt" srclang="es" label="Spanish" />\n</video>',
        },
      },
      {
        type: 'paragraph',
        text: 'In order to try this you need to host the files on a local HTTP server. In the output in browser, you\'ll see a video that has subtitles displayed. For a full-fledged application and its source code, see Adding captions and subtitles to HTML video. This example uses JavaScript to allow users to choose between different subtitles. Note that to turn the subtitles on, you need to press the "CC" button and select an option — English, Deutsch, or Español.',
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'Text tracks also help you with SEO, since search engines especially thrive on text. Text tracks even allow search engines to link directly to a spot partway through the video.',
        },
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/HTML_video_and_audio',
  },
  'html-video-and-audio-embedding-your-own-audio-and-video': {
    id: 'html-video-and-audio-embedding-your-own-audio-and-video',
    heading: 'Embedding your own audio and video',
    blocks: [
      {
        type: 'paragraph',
        text: "For this task, why not go out into the world and record some of your own video and audio? If you have a phone, use that to record audio and video, transfer it to your computer, and try it out. You may have to do some conversion to end up with a WebM and MP4 in the case of video, and an MP3 and Ogg in the case of audio, but there are enough programs and tools out there to allow you to do this without too much trouble, such as CloudConvert (online) and Audacity (desktop application). We'd like you to have a go!",
      },
      {
        type: 'callout',
        callout: {
          variant: 'info',
          title: 'Note',
          body: 'If you are unable to source any video or audio, then you can feel free to use our sample audio and video files to carry out this exercise.',
        },
      },
      {
        type: 'paragraph',
        text: 'We would like you to:',
      },
      {
        type: 'list',
        ordered: true,
        items: [
          'Save your audio and video files in a new directory on your computer.',
          'Create a new HTML file in the same directory, called `index.html`, based on our getting started template.',
          'Add `<audio>` and `<video>` elements to the page; make them display the default browser controls.',
          'Give both of them `<source>` elements so that browsers will find the audio format they support best and load it. These should include `type` attributes.',
          'Give both of them a fallback `<p>` element inside the tags that provides a direct link to the media for non-supporting browsers.',
          'Give the `<video>` element a poster that will be displayed before the video starts to be played. Have fun creating your own poster graphic.',
        ],
      },
    ],
    sourceUrl:
      'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/HTML_video_and_audio',
  },
};
