// Generated by scripts/draft-to-topics.mjs from an MDN import, then hand-reviewed.
// Content adapted from MDN Web Docs (https://developer.mozilla.org), licensed CC BY-SA.
import type { ContentTopic } from '../../types';

export const webFormsTopics: Record<string, ContentTopic> = {
  'web-forms-prerequisites': {
    id: 'web-forms-prerequisites',
    heading: 'Prerequisites',
    blocks: [
      {
        type: 'paragraph',
        text: 'Before starting this module, you should at least work through our Introduction to HTML. At this point you should find the Introductory tutorials easy to understand, and also be able to make use of our Basic native form controls tutorial.',
      },
      {
        type: 'paragraph',
        text: "Mastering forms however requires more than just HTML knowledge — you also need to learn some specific techniques to style form controls, and some scripting knowledge is required to handle things like validation and creating custom form controls. Therefore, before you look at the other sections listed below we'd recommend that you go away and learn some CSS and JavaScript first.",
      },
      {
        type: 'paragraph',
        text: "The above text is a good indicator as to why we've put web forms into its own standalone module, rather than trying to mix bits of it into the HTML, CSS, and JavaScript topic areas — form elements are more complex than most other HTML elements, and they also require a close marriage of related CSS and JavaScript techniques to get the most out of them.",
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms',
  },
  'web-forms-introductory-tutorials': {
    id: 'web-forms-introductory-tutorials',
    heading: 'Introductory tutorials',
    blocks: [
      {
        type: 'definitions',
        items: [
          {
            term: 'Your first form',
            description:
              'The first article in our series provides your very first experience of creating a web form, including designing a simple form, implementing it using the right HTML elements, adding some very simple styling via CSS, and how data is sent to a server.',
          },
          {
            term: 'How to structure a web form',
            description:
              'With the basics out of the way, we now look in more detail at the elements used to provide structure and meaning to the different parts of a form.',
          },
        ],
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms',
  },
  'web-forms-the-different-form-controls': {
    id: 'web-forms-the-different-form-controls',
    heading: 'The different form controls',
    blocks: [
      {
        type: 'definitions',
        items: [
          {
            term: 'Basic native form controls',
            description:
              'We start off this section by looking at the functionality of the original HTML `<input>` types in detail, looking at what options are available to collect different types of data.',
          },
          {
            term: 'The HTML5 input types',
            description:
              'Here we continue our deep dive into the `<input>` element, looking at the additional input types provided when HTML5 was released, and the various UI controls and data collection enhancements they provide. Additionally, we look at the `<output>` element.',
          },
          {
            term: 'Other form controls',
            description:
              'Next we take a look at all the non-`<input>` form controls and associated tools, such as `<select>`, `<textarea>`, `<meter>`, and `<progress>`.',
          },
        ],
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms',
  },
  'web-forms-form-styling-tutorials': {
    id: 'web-forms-form-styling-tutorials',
    heading: 'Form styling tutorials',
    blocks: [
      {
        type: 'definitions',
        items: [
          {
            term: 'Styling web forms',
            description:
              'This article provides an introduction to styling forms with CSS, including all the basics you might need to know for basic styling tasks.',
          },
          {
            term: 'Advanced form styling',
            description:
              'Here we look at some more advanced form styling techniques that need to be used when trying to deal with some of the more difficult-to-style form elements.',
          },
          {
            term: 'Customizable select elements',
            description:
              'This article explains how to use dedicated, modern HTML and CSS features together to create fully-customized `<select>` elements. This includes having full control over styling the select button, drop-down picker, arrow icon, current selection checkmark, and each individual `<option>` element.',
          },
          {
            term: 'Customizable select listboxes',
            description:
              'This article follows on from the previous one, looking at how to style customizable listbox `<select>` elements.',
          },
          {
            term: 'UI pseudo-classes',
            description:
              'An introduction to the UI pseudo-classes enabling HTML form controls to be targeted based on their current state.',
          },
        ],
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms',
  },
  'web-forms-validating-and-submitting-form-data': {
    id: 'web-forms-validating-and-submitting-form-data',
    heading: 'Validating and submitting form data',
    blocks: [
      {
        type: 'definitions',
        items: [
          {
            term: 'Client-side form validation',
            description:
              "Sending data is not enough — we also need to make sure that the data users enter into forms is in the correct format to process it successfully, and that it won't break our applications. We also want to help our users to fill out our forms correctly and not get frustrated when trying to use our apps. Form validation helps us achieve these goals — this article tells you what you need to know.",
          },
          {
            term: 'Sending form data',
            description:
              'This article looks at what happens when a user submits a form — where does the data go, and how do we handle it when it gets there? We also look at some of the security concerns associated with sending form data.',
          },
        ],
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms',
  },
  'web-forms-additional-tutorials': {
    id: 'web-forms-additional-tutorials',
    heading: 'Additional tutorials',
    blocks: [
      {
        type: 'paragraph',
        text: "The following articles aren't included in the learning pathway, but they'll prove interesting and useful when you've mastered the above techniques and want to know more.",
      },
      {
        type: 'definitions',
        items: [
          {
            term: 'How to build custom form controls',
            description:
              "You'll come across some cases where the native form widgets just don't provide what you need, e.g., because of styling or functionality. In such cases, you may need to build your own form widget out of raw HTML. This article explains how you'd do this and the considerations you need to be aware of when doing so, with a practical case study.",
          },
          {
            term: 'Sending forms through JavaScript',
            description:
              "This article looks at ways to use a form to assemble an HTTP request and send it via custom JavaScript, rather than standard form submission. It also looks at why you'd want to do this, and the implications of doing so. (See also Using FormData objects.)",
          },
          {
            term: 'HTML forms in legacy browsers',
            description:
              'This article provides tips and tricks to help ease the pain if, and when, you need to support legacy browsers with your HTML forms.',
          },
          {
            term: 'User input methods and controls',
            description:
              'This article shows the different ways that users interact with forms and other web content, and provides recommendations for managing user input, real-world examples, and links to further information.',
          },
        ],
      },
    ],
    sourceUrl: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms',
  },
};
